// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: async_api_status (core)

import type { ListEnvelope, BatchResponse } from "./shared";

export interface AsyncApiStatus {
	/** Status of the message */
	status?: string;
	/** Profile Id of the message */
	efEntityId?: string;
	/** Profile Id of the message */
	externalEntityId?: string;
}

export type AsyncApiStatusList = ListEnvelope<AsyncApiStatus>;
export type AsyncApiStatusBatch = BatchResponse<AsyncApiStatus>;
