// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: ats_position (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface AtsPosition {
	/** all the activities related to this positions */
	activities?: {
		activityTime?: number;
		activityType?: string;
		changeLogs?: {
		fieldName?: string;
		newValue?: string;
		prevValue?: string;
	}[];
		message?: string;
	}[];
	/** position_id in the ats system */
	atsEntityId?: string;
	/** ATS attribute which identifies the job this jobrequestion is mapped to */
	jobCode?: string;
	/** business unit */
	businessUnit?: string;
	/** company */
	company?: string;
	/** Company description */
	companyDescription?: string;
	/** all the coordinators related to this position */
	coordinators?: {
		email?: string;
		name?: string;
	}[];
	/** creation timestamp in epoch format */
	createdAt?: number;
	/** Email of the user who created this position */
	createdBy?: string;
	/** custom fields */
	customFields?: Record<string, unknown>;
	/** job description */
	description?: string;
	/** display job id */
	displayJobId?: string;
	/** Employment Type */
	employmentType?: string;
	/** is evergreen */
	evergreen?: boolean;
	/** all the followers of the positions as hiring managers etc. */
	followers?: {
		email?: string;
		name?: string;
	}[];
	/** job function */
	function?: string;
	/** hiring band */
	hiringBand?: string;
	/** Hiring Manager */
	hiringManager?: {
		email?: string;
		name?: string;
	};
	/** internal posting url */
	internalPostingUrl?: string;
	/** job postings */
	jobPosts?: {
		expirationTime?: number;
		jobDescription?: string;
		postedFor?: string;
		postingId?: string;
		postingTitle?: string;
		primaryPost?: boolean;
		publishedTime?: number;
		locale?: string;
	}[];
	/** job_stages */
	jobStages?: string[];
	/** last modified date time in epoch format */
	lastUpdated?: number;
	/** location */
	locations?: string[];
	/** status of the position open or not */
	open?: boolean;
	/** Openings */
	openings?: {
		numOpenings?: number;
		numOpeningsFilled?: number;
		openingDetails?: {
		openingId?: string;
		status?: string;
		openedAt?: number;
		closedAt?: number;
		applicationId?: string;
		candidateId?: string;
		closeReason?: string;
	}[];
		openedAt?: number;
		closedAt?: number;
	};
	/** status of the position posted or not */
	posted?: boolean;
	/** internal for internal jobs, external for external jobs, */
	postedFor?: string;
	/** posting title */
	postingTitle?: string;
	/** posting url */
	postingUrl?: string;
	/** EF Position ID */
	positionId?: number;
	/** questions */
	questions?: {
		choices?: {
		label?: string;
		value?: string;
	}[];
		choicesV2?: {
		label?: string;
		value?: string;
		langMappingList?: {
		locale?: string;
		label?: string;
	}[];
	}[];
		required?: boolean;
		type?: string;
		questionId?: string;
		help?: string;
		question?: {
		label?: string;
		value?: string;
		langMappingList?: {
		locale?: string;
		label?: string;
	}[];
	};
	}[];
	/** questionnaires */
	questionnaires?: {
		questionnaireId?: string;
		questionDependencies?: {
		questionId?: string;
		choiceValue?: string;
		questionSource?: string;
		childQuestionIds?: string[];
		dependencyType?: string;
	}[];
	}[];
	/** recruiter */
	recruiter?: {
		email?: string;
		name?: string;
	};
	/** Requisition Type */
	requisitionType?: string;
	/** required skills */
	requiredSkills?: string[];
	/** restrict access */
	restrictAccess?: boolean;
	/** skills */
	skills?: string[];
	/** all the recruiters/sourcers related to this positions */
	sourcers?: {
		email?: string;
		name?: string;
	}[];
	/** start date of the position in ISO 8601 format (e.g. 2024-05-01) */
	startDate?: string;
	/** status */
	status?: string;
	/** system id */
	systemId?: string;
	/** job title */
	title?: string;
	/** Indicates the option for working location e.g. onsite, remote_global, remote_local, hybrid */
	workLocationOption?: string;
	/** Indicates the flexibility on location e.g. not_flexible, flexible_within_country, flexible_global */
	locationFlexibility?: string;
	/** Indicates which workflow this position belongs to */
	workflowTemplateId?: string;
	/** Indicates if a position is a private posting */
	isPrivate?: boolean;
	/** City of the location */
	locationCity?: string;
	/** State of the location */
	locationState?: string;
	/** Country of the location */
	locationCountry?: string;
	/** Template id of the template used to create the position */
	templateId?: number;
	/** Org units of the position */
	orgUnits?: Record<string, unknown>;
	/** ATS user groups */
	atsUserGroups?: {
		userGroupId?: string;
	}[];
	/** Unified hiring team array. Each entry: {role, roleKey, name, email}. Includes primary/secondary HMs, primary/secondary recruiters, and custom roles. */
	hiringTeam?: {
		role?: string;
		roleKey?: string;
		name?: string;
		email?: string;
	}[];
}

export interface AtsPositionListFilters extends BaseListFilters {
	/** Filter query using predefined filter arguments documented [here](https://apidocs.eightfold.ai/v2.0/docs#the-filterquery-parameter) */
	filterQuery?: string;
	/** any wildcard text to search in position */
	query?: string;
}

export type AtsPositionList = ListEnvelope<AtsPosition>;
export type AtsPositionBatch = BatchResponse<AtsPosition>;
