// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: ats_candidate (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface AtsCandidate {
	/** address of candidate */
	address?: string;
	/** applications of candidates */
	applications?: {
		applicationId?: string;
		applicationTs?: number;
		candidateId?: string;
		creditor?: string;
		currentStage?: {
		reason?: string;
		stageTs?: number;
		user?: {
		atsRoles?: string[];
		email?: string;
		name?: string;
		userId?: string;
	};
		wfStage?: string;
		wfSubStage?: string;
		stage?: string;
	};
		customInfo?: Record<string, unknown>;
		disabilityStatus?: boolean;
		disabilityStatusStr?: string;
		gender?: string;
		hiredTs?: number;
		isProspect?: boolean;
		jobSystemId?: string;
		jobs?: {
		atsJobId?: string;
		name?: string;
	}[];
		lastModifiedTs?: number;
		location?: string;
		locationCountry?: string;
		note?: {
		body?: string;
		cc?: string[];
		creationTs?: number;
		creator?: string;
		noteType?: string;
		sender?: string;
		subject?: string;
		to?: string;
		visibility?: string;
	};
		pastStages?: {
		reason?: string;
		stageTs?: number;
		user?: {
		atsRoles?: string[];
		email?: string;
		name?: string;
		userId?: string;
	};
		wfStage?: string;
		wfSubStage?: string;
		stage?: string;
	}[];
		questions?: {
		answer?: string[];
		choices?: string[];
		displayOrder?: string;
		explanation?: string;
		formId?: string;
		formName?: string;
		formType?: string;
		question?: string;
		questionId?: string;
		type?: string;
	}[];
		races?: string[];
		reason?: string;
		rejectedBy?: string;
		rejectedTs?: number;
		scorecards?: {
		attributes?: {
		question?: string;
		answer?: string;
		note?: string;
		rating?: string;
		rating_label?: string;
	}[];
		description?: string;
		interviewName?: string;
		interviewedAt?: number;
		overallRating?: string;
		overallRatingLabel?: string;
		submittedAt?: number;
		submittedBy?: {
		atsRoles?: string[];
		email?: string;
		name?: string;
		userId?: string;
	};
	}[];
		sourceName?: string;
		sourceType?: string;
		status?: string;
		systemId?: string;
		veteranStatus?: boolean;
		veteranStatusStr?: string;
		visaStatuses?: string[];
	}[];
	/** Attachments of candidate */
	attachments?: {
		applicationMetadata?: {
		applicationId?: string;
	}[];
		attachmentId?: string;
		attachmentType?: string;
		attachmentContent?: string;
		fileName?: string;
		isBase64?: boolean;
		lastModifiedTs?: number;
	}[];
	/** ATS Candidate id */
	candidateId?: string;
	/** certifications for candidate */
	certifications?: {
		certificateName?: string;
		endTs?: number;
		issuingAuthority?: string;
		licenseNo?: string;
		proficiency?: string;
		startTs?: number;
		validFromTs?: number;
		validToTs?: number;
		verificationStatus?: string;
		verificationBy?: string;
		verificationTs?: number;
		certificateExternalId?: string;
		attachmentIds?: string[];
		locationState?: string;
		locationCountry?: string;
		status?: string;
		comments?: string;
		description?: string;
		certificateType?: string;
		skills?: string[];
		allText?: string;
	}[];
	/** Contact consent for candidate. Valid inputs: applied_only, all, country_only */
	contactConsent?: string;
	/** course attandance of candidate */
	courseAttendance?: {
		lmsCourseId?: string;
		title?: string;
		description?: string;
		courseType?: string;
		language?: string;
		difficulty?: string;
		startTs?: number;
		completionTs?: number;
		courseUrl?: string;
		provider?: string;
		isInternal?: boolean;
		status?: string;
		pointsEarned?: number;
		verified?: string;
		medium?: string;
		isMandatory?: boolean;
		assignedBy?: string;
		percentageCompletion?: number;
		durationHours?: number;
		dueTs?: number;
	}[];
	/** custom info of candidate */
	customInfo?: Record<string, unknown>;
	/** date of birth of candidate */
	dateOfBirth?: string;
	/** detail tags of candidate */
	detailTags?: {
		creationTs?: number;
		creator?: string;
		jobId?: string;
		tag?: string;
		tagSubtype?: string;
		tagType?: string;
	}[];
	/** disability status */
	disabilityStatus?: boolean;
	/** disability status of an applicant */
	disabilityStatusStr?: string;
	/** display tags for candidate */
	displayTags?: string[];
	/** education of candidate */
	education?: {
		degree?: string;
		description?: string;
		endTs?: number;
		location?: string;
		major?: string;
		school?: string;
		startTs?: number;
		nameAlias?: string;
		verificationStatus?: string;
		isGraduated?: boolean;
		verificationBy?: string;
		schoolExternalId?: string;
		degreeExternalId?: string;
		majorExternalId?: string;
		verificationTs?: number;
		attachmentIds?: string[];
		isCurrent?: boolean;
	}[];
	/** email of candidate */
	emails?: string;
	/** experience of candidate */
	experience?: {
		company?: string;
		department?: string;
		description?: string;
		endTs?: number;
		industry?: string;
		isCurrent?: boolean;
		isInternal?: boolean;
		location?: string;
		startTs?: number;
		title?: string;
	}[];
	/** first name of candidate */
	firstName?: string;
	/** gender of candidate */
	gender?: string;
	/** highest education level of candidate */
	highestEducationLevel?: string;
	/** is anonymized candidate */
	isAnonymized?: boolean;
	/** is internal candidate */
	isInternal?: boolean;
	/** last activity time stamp of candidate */
	lastActivityTs?: number;
	/** last name of candidate */
	lastName?: string;
	/** location of candidate */
	location?: string;
	/** location country of candidate */
	locationCountry?: string;
	/** notes of candidates */
	notes?: {
		body?: string;
		cc?: string[];
		creationTs?: number;
		creator?: string;
		noteType?: string;
		sender?: string;
		subject?: string;
		to?: string;
		visibility?: string;
	}[];
	/** comma separated phone numbers of candidate */
	phones?: string;
	/** Photo content. */
	photoContent?: {
		content?: string;
		extension?: string;
		isBase64?: boolean;
	};
	/** project of candidate */
	project?: {
		company?: string;
		contributors?: string[];
		description?: string;
		endTs?: number;
		links?: string[];
		skills?: string[];
		startTs?: number;
		title?: string;
	}[];
	/** questions of candidate */
	questions?: {
		answer?: string[];
		choices?: string[];
		displayOrder?: string;
		explanation?: string;
		formId?: string;
		formName?: string;
		formType?: string;
		question?: string;
		questionId?: string;
		type?: string;
	}[];
	/** race of candidate */
	races?: string[];
	/** Resume content for candidate. */
	resumeContent?: {
		content?: string;
		extension?: string;
		isBase64?: boolean;
	};
	/** scheduled interviews of candidate */
	scheduledInterviews?: {
		startTs?: number;
		endTs?: number;
		location?: string;
		status?: string;
		organizer?: string;
		interviewers?: string[];
		comment?: string;
		referenceId?: string;
		interviewType?: string;
	}[];
	/** skill details of candidate */
	skillDetails?: {
		dataSource?: string;
		proficiency?: string;
		skill?: string;
		skillGroups?: {
		skillGroup?: string;
		proficiency?: string;
	}[];
	}[];
	/** skills of candidate */
	skills?: string[];
	/** summary of candidate */
	summary?: string;
	/** system if of candidate */
	systemId?: string;
	/** tags of candidate */
	tags?: string[];
	/** title of candidate */
	title?: string;
	/** urls of candidate */
	urls?: string[];
	/** Boolean value for veteran status of the candidate */
	veteranStatus?: boolean;
	/** String value for veteran status of the candidate */
	veteranStatusStr?: string;
	/** visa statuses of candidate */
	visaStatuses?: string[];
}

export interface AtsCandidateListFilters extends BaseListFilters {
	/** filter query using predefined filter arguments documented [here](https://apidocs.eightfold.ai/v2.0/docs#the-filterquery-parameter) */
	filterQuery?: string;
	/** any wildcard text to search in position */
	query?: string;
}

export type AtsCandidateList = ListEnvelope<AtsCandidate>;
export type AtsCandidateBatch = BatchResponse<AtsCandidate>;
