// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: booking (resource_management)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface Booking {
	data?: unknown[];
	meta?: unknown;
}

export interface BookingListFilters extends BaseListFilters {
	/** Filter on employee's email */
	employeeEmail?: string;
	/** Filter on Eightfold demand id */
	demandId?: string;
	/** The start date of the period for which you want to filter bookings. This parameter accepts an epoch timestamp. Only bookings that end on or after this date will be included in the response. */
	startDate?: string;
	/** The end date of the period for which you want to filter bookings. This parameter accepts an epoch timestamp. Only bookings that start on or before this date will be included in the response. */
	endDate?: string;
	/** Filter on booking type. Possible values: ['demand', 'leave', 'optional_holiday', 'blocker'] */
	bookingType?: string;
	/** Filter on booking status. Possible values: ['pending', 'approved', 'rejected'] */
	bookingStatus?: string;
}

export type BookingList = ListEnvelope<Booking>;
export type BookingBatch = BatchResponse<Booking>;
