// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: career_navigator (careerhub)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface CareerNavigator {
	/** List of career paths */
	careerPaths?: {
		pathHighlights?: string[];
		roleList?: {
		entityId?: number;
		title?: string;
		isCareerInterest?: boolean;
		highlights?: string[];
		recommendedPositionsCount?: number;
		associatedEmployeesData?: {
		associatedEmployeesCount?: number;
		associatedEmployeesProfiles?: {
		currentTitle?: string;
		encId?: string;
		imageUrl?: string;
		name?: string;
	}[];
	};
		skillData?: {
		matchingSkills?: string[];
		roleSkills?: string[];
		requiredSkills?: string[];
		matchingRequiredSkills?: string[];
	};
	}[];
	}[];
	/** User additional data */
	userAdditionalData?: {
		currentRole?: {
		entityId?: number;
		title?: string;
		isCareerInterest?: boolean;
		highlights?: string[];
		recommendedPositionsCount?: number;
		associatedEmployeesData?: {
		associatedEmployeesCount?: number;
		associatedEmployeesProfiles?: {
		currentTitle?: string;
		encId?: string;
		imageUrl?: string;
		name?: string;
	}[];
	};
		skillData?: {
		matchingSkills?: string[];
		roleSkills?: string[];
		requiredSkills?: string[];
		matchingRequiredSkills?: string[];
	};
	};
		currentTenure?: string;
	};
}

export interface CareerNavigatorListFilters extends BaseListFilters {
	/** Role ID */
	roleId: string;
}

export type CareerNavigatorList = ListEnvelope<CareerNavigator>;
export type CareerNavigatorBatch = BatchResponse<CareerNavigator>;
