// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: careerhub (careerhub)

import type { ListEnvelope, BatchResponse } from "./shared";

export interface Careerhub {
	[key: string]: unknown;
}

export type CareerhubList = ListEnvelope<Careerhub>;
export type CareerhubBatch = BatchResponse<Careerhub>;
