// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: connectors (connectors)

import type { ListEnvelope, BatchResponse } from "./shared";

export interface Connectors {
	[key: string]: unknown;
}

export type ConnectorsList = ListEnvelope<Connectors>;
export type ConnectorsBatch = BatchResponse<Connectors>;
