// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: course (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface Course {
	/** ID of the course */
	courseId?: string;
	/** Group id of the course */
	groupId?: string;
	/** System id for the course */
	systemId?: string;
	/** lms course id */
	lmsCourseId?: string;
	/** title of course */
	title?: string;
	/** Description of course */
	description?: string;
	/** course type */
	courseType?: string;
	/** language */
	language?: string;
	/** Difficulty of course */
	difficulty?: string;
	/** Duration hours of course */
	durationHours?: number;
	/** Publication date of course */
	publishedDate?: string;
	/** url of the course */
	courseUrl?: string;
	/** status of course */
	status?: string;
	/** course category */
	category?: string;
	/** image url of course */
	imageUrl?: string;
	/** provider of course */
	provider?: string;
	/** skills related to course */
	skills?: string[];
	/** Eightfold-detected course skills based on title and description */
	efSkills?: string[];
	/** Average rating of the course */
	rating?: number;
	/** Number of ratings submitted for the course */
	ratingCount?: number;
}

export interface CourseListFilters extends BaseListFilters {
	/** Any wildcard text to search in courses */
	query?: string;
	/** Provides recommended courses for a given profileId, this feature does not support query addition. */
	recommendedFor?: string;
	/** This field can be utilized to surface courses with type certificate in course search. By default non certificate type courses are exposed. Use course type value as certificate to filter them out. */
	courseType?: string;
}

export type CourseList = ListEnvelope<Course>;
export type CourseBatch = BatchResponse<Course>;
