// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: demand (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface Demand {
	data?: unknown[];
	meta?: unknown;
}

export interface DemandListFilters extends BaseListFilters {
	/** unique identifier in the external system */
	extDemandId?: string;
	/** Filter query using predefined filter arguments documented [here](https://apidocs.eightfold.ai/v2.0/docs#the-filterquery-parameter) */
	filterQuery?: string;
	/** any wildcard text to search in demand */
	query?: string;
	/** Include archived demands */
	includeArchived?: boolean;
}

export type DemandList = ListEnvelope<Demand>;
export type DemandBatch = BatchResponse<Demand>;
