// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: email_delivery_feedback (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface EmailDeliveryFeedback {
	/** Unique Id associated with this email delivery feedback */
	id?: number;
	/** Type of feedback for this email delivery feedback */
	feedbackType?: string;
	/** Email to address associated with the feedback */
	email?: string;
	/** Email from address associated with the feedback */
	sourceEmail?: string;
	/** Timestamp when this email delivery feedback was created */
	createdAt?: number;
}

export interface EmailDeliveryFeedbackListFilters extends BaseListFilters {
	/** Limit on the total number of search results, defaults to 100 */
	queryLimit?: string;
	/** To Email address field to filter on */
	email?: string;
}

export type EmailDeliveryFeedbackList = ListEnvelope<EmailDeliveryFeedback>;
export type EmailDeliveryFeedbackBatch = BatchResponse<EmailDeliveryFeedback>;
