// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: employee (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface Employee {
	/** The additional managers of the employee */
	additionalManagers?: {
		capacityManagerEmail?: string;
	}[];
	/** The unique id of the Employee in the HRIS system */
	employeeId?: string;
	/** Profile id of the Employee in Eightfold */
	id?: string;
	/** The userId of the employee */
	userId?: string;
	/** First Name of the employee */
	firstName?: string;
	/** Last Name of the employee */
	lastName?: string;
	/** List of Emails of the employee comma seperated */
	email?: string;
	/** The business email of the employee */
	businessEmail?: string;
	/** The personal email of the employee */
	personalEmail?: string;
	/** Type of the employee */
	employeeType?: string;
	/** External job id of the employee */
	externalJobId?: string;
	/** candidate data of employee */
	candidateData?: {
		candidateId?: string;
		address?: string;
		location?: string;
		locationCountry?: string;
		dateOfBirth?: string;
		gender?: string;
		races?: string[];
		summary?: string;
		education?: {
		degree?: string;
		description?: string;
		endTs?: number;
		location?: string;
		major?: string;
		school?: string;
		startTs?: number;
		nameAlias?: string;
		verificationStatus?: string;
		isGraduated?: boolean;
		verificationBy?: string;
		schoolExternalId?: string;
		degreeExternalId?: string;
		majorExternalId?: string;
		verificationTs?: number;
		attachmentIds?: string[];
		isCurrent?: boolean;
	}[];
		certifications?: {
		certificateName?: string;
		endTs?: number;
		issuingAuthority?: string;
		licenseNo?: string;
		proficiency?: string;
		startTs?: number;
		validFromTs?: number;
		validToTs?: number;
		verificationStatus?: string;
		verificationBy?: string;
		verificationTs?: number;
		certificateExternalId?: string;
		attachmentIds?: string[];
		locationState?: string;
		locationCountry?: string;
		status?: string;
		comments?: string;
		description?: string;
		certificateType?: string;
		skills?: string[];
		allText?: string;
	}[];
		urls?: string[];
		photoContent?: {
		content?: string;
		extension?: string;
		isBase64?: boolean;
	};
		experience?: {
		company?: string;
		department?: string;
		description?: string;
		endTs?: number;
		industry?: string;
		isCurrent?: boolean;
		isInternal?: boolean;
		location?: string;
		startTs?: number;
		title?: string;
	}[];
		project?: {
		company?: string;
		contributors?: string[];
		description?: string;
		endTs?: number;
		links?: string[];
		skills?: string[];
		startTs?: number;
		title?: string;
	}[];
		courseAttendance?: {
		lmsCourseId?: string;
		title?: string;
		description?: string;
		courseType?: string;
		language?: string;
		difficulty?: string;
		startTs?: number;
		completionTs?: number;
		courseUrl?: string;
		provider?: string;
		isInternal?: boolean;
		status?: string;
		pointsEarned?: number;
		verified?: string;
		medium?: string;
		isMandatory?: boolean;
		assignedBy?: string;
		percentageCompletion?: number;
		durationHours?: number;
		dueTs?: number;
	}[];
		customInfo?: Record<string, unknown>;
		attachments?: {
		applicationMetadata?: {
		applicationId?: string;
	}[];
		attachmentId?: string;
		attachmentType?: string;
		attachmentContent?: string;
		fileName?: string;
		isBase64?: boolean;
		lastModifiedTs?: number;
	}[];
		skills?: string[];
		applications?: {
		applicationId?: string;
		applicationTs?: number;
		candidateId?: string;
		creditor?: string;
		currentStage?: {
		reason?: string;
		stageTs?: number;
		user?: {
		atsRoles?: string[];
		email?: string;
		name?: string;
		userId?: string;
	};
		wfStage?: string;
		wfSubStage?: string;
		stage?: string;
	};
		customInfo?: Record<string, unknown>;
		disabilityStatus?: boolean;
		disabilityStatusStr?: string;
		gender?: string;
		hiredTs?: number;
		isProspect?: boolean;
		jobSystemId?: string;
		jobs?: {
		atsJobId?: string;
		name?: string;
	}[];
		lastModifiedTs?: number;
		location?: string;
		locationCountry?: string;
		note?: {
		body?: string;
		cc?: string[];
		creationTs?: number;
		creator?: string;
		noteType?: string;
		sender?: string;
		subject?: string;
		to?: string;
		visibility?: string;
	};
		pastStages?: {
		reason?: string;
		stageTs?: number;
		user?: {
		atsRoles?: string[];
		email?: string;
		name?: string;
		userId?: string;
	};
		wfStage?: string;
		wfSubStage?: string;
		stage?: string;
	}[];
		questions?: {
		answer?: string[];
		choices?: string[];
		displayOrder?: string;
		explanation?: string;
		formId?: string;
		formName?: string;
		formType?: string;
		question?: string;
		questionId?: string;
		type?: string;
	}[];
		races?: string[];
		reason?: string;
		rejectedBy?: string;
		rejectedTs?: number;
		scorecards?: {
		attributes?: {
		question?: string;
		answer?: string;
		note?: string;
		rating?: string;
		rating_label?: string;
	}[];
		description?: string;
		interviewName?: string;
		interviewedAt?: number;
		overallRating?: string;
		overallRatingLabel?: string;
		submittedAt?: number;
		submittedBy?: {
		atsRoles?: string[];
		email?: string;
		name?: string;
		userId?: string;
	};
	}[];
		sourceName?: string;
		sourceType?: string;
		status?: string;
		systemId?: string;
		veteranStatus?: boolean;
		veteranStatusStr?: string;
		visaStatuses?: string[];
	}[];
		tags?: string[];
		displayTags?: string[];
		skillDetails?: {
		dataSource?: string;
		proficiency?: string;
		skill?: string;
		skillGroups?: {
		skillGroup?: string;
		proficiency?: string;
	}[];
	}[];
		awards?: {
		allText?: string;
		date?: string;
		description?: string;
		entity?: string;
		title?: string;
		skills?: string[];
	}[];
		patents?: {
		allText?: string;
		date?: string;
		description?: string;
		title?: string;
		skills?: string[];
	}[];
		publications?: {
		date?: string;
		description?: string;
		publisher?: string;
		title?: string;
		skills?: string[];
	}[];
	};
	/** Projects of the employee */
	projects?: {
		company?: string;
		contributors?: string[];
		personal_description?: string;
		description?: string;
		duration?: number;
		feedback?: {
		comment?: string;
		imageUrl?: string;
		name?: string;
		profileId?: number;
		projectId?: number;
		rating?: string;
		timestamp?: number;
	}[];
		links?: string[];
		projectId?: string;
		skills?: string[];
		time?: string;
		title?: string;
		addlJson?: Record<string, unknown>;
	}[];
	/** Education of the employee */
	education?: {
		awards?: string[];
		degree?: string;
		description?: string;
		endTime?: number;
		major?: string;
		location?: string;
		school?: string;
		startTime?: number;
		isCurrent?: boolean;
		nameAlias?: string;
		verificationStatus?: string;
		isGraduated?: boolean;
		verificationBy?: string;
		schoolExternalId?: string;
		degreeExternalId?: string;
		majorExternalId?: string;
		verificationTs?: number;
		source?: string;
		attachmentIds?: string[];
	}[];
	/** Experiences of the employee */
	experiences?: {
		addlJson?: Record<string, unknown>;
		department?: string;
		description?: string;
		durationMonths?: number;
		edited?: boolean;
		endTime?: number;
		experienceKey?: string;
		industry?: string;
		isCurrent?: boolean;
		isInternal?: boolean;
		location?: string;
		skills?: string[];
		startTime?: number;
		title?: string;
		userVerifiedSkills?: boolean;
		work?: string;
	}[];
	/** Certificates of the employee */
	certificates?: {
		description?: string;
		certificateType?: string;
		title?: string;
		date?: string;
		issuingAuthority?: string;
		status?: string;
		country?: string;
		state?: string;
		externalKey?: string;
		certificateId?: string;
		endDate?: string;
		startDate?: string;
		validFromDate?: string;
		validToDate?: string;
		proficiency?: string;
		verificationStatus?: string;
		verificationBy?: string;
		verificationTs?: number;
		certificateExternalId?: string;
		source?: string;
		attachmentIds?: string[];
		skills?: string[];
		allText?: string[];
		comments?: string;
	}[];
	/** Awards listed on employee profile */
	awards?: {
		allText?: string;
		date?: string;
		description?: string;
		entity?: string;
		title?: string;
		skills?: string[];
	}[];
	/** Patents listed on employee profile */
	patents?: {
		allText?: string;
		date?: string;
		description?: string;
		title?: string;
		skills?: string[];
	}[];
	/** Publications listed on employee profile */
	publications?: {
		date?: string;
		description?: string;
		publisher?: string;
		title?: string;
		skills?: string[];
	}[];
	/** The role of the employee */
	role?: string;
	/** The job code of the employee */
	jobCode?: string;
	/** Integration system id for the employee */
	systemId?: string;
	/** The company name of the employee */
	companyName?: string;
	/** The title of the employee */
	title?: string;
	/** The job level of the employee */
	level?: string;
	/** The location of the employee */
	location?: string;
	/** The location country of the employee */
	locationCountry?: string;
	/** The hiring timestamp of the employee in seconds */
	hiringTs?: number;
	/** The last role timestamp of the employee in seconds */
	roleChangeTs?: number;
	/** The user id of the manager in HRIS system */
	managerUserId?: string;
	/** The email of the manager */
	managerEmail?: string;
	/** The contact email of the manager */
	managerContactEmail?: string;
	/** The full name of the manager */
	managerFullname?: string;
	/** The Business unit of the employee */
	bu?: string;
	/** The lob of the employee */
	lob?: string;
	/** The termination timestamp of the employee in seconds */
	terminationTs?: number;
	/** The phone number of the employee */
	phone?: string;
	/** The last activity timestamp in seconds */
	lastActivityTs?: number;
	/** The last updated timestamp of the employee profile */
	lastUpdatedTs?: number;
	/** Is contingent */
	isContingent?: boolean;
	/** The badges of the employee */
	badges?: {
		badgeId?: string;
		comment?: string;
		creator?: string;
		lastModifiedTs?: number;
		photoContent?: {
		content?: string;
		extension?: string;
		isBase64?: boolean;
	};
		photoUrl?: string;
		title?: string;
		userId?: string;
	}[];
	/** The base pay of the employee */
	basePay?: {
		amount?: number;
		currency?: string;
		frequency?: string;
	};
	/** The bonus given to the employee */
	bonus?: {
		amount?: number;
		currency?: string;
		frequency?: string;
	};
	/** The last review rating of the employee */
	lastReviewRating?: string;
	/** Is the employee eligible for transfer or not */
	eligibleForTransfer?: boolean;
	/** The custom info captured for the employee by custom fields */
	customInfo?: Record<string, unknown>;
	/** The criticality information of the employee */
	employeeCriticality?: {
		riskOfLoss?: string;
		impactOfLoss?: string;
	};
	/** The criticality of the position of the employee */
	positionCriticality?: string[];
	/** The employee language proficiencies */
	languages?: {
		language?: string;
		overall?: string;
		write?: string;
		read?: string;
		speak?: string;
	}[];
	/** The mobility of the employee */
	mobility?: {
		relocation?: string;
		relocationLocations?: string[];
		travel?: string;
		comments?: string;
		travelPercentageMin?: number;
		travelPercentageMax?: number;
	};
	/** Performance ratings for the employee */
	performanceRatings?: {
		periodStartDate?: string;
		periodEndDate?: string;
		rating?: number;
		ratingLabel?: string;
		reviewType?: string;
		reviewComments?: string;
		reviewedBy?: {
		firstName?: string;
		lastName?: string;
		atsRoles?: string[];
		email?: string;
		name?: string;
		userId?: string;
		atsUserGroups?: {
		userGroupId?: string;
	}[];
	};
	}[];
	/** Succession plan for the employee */
	successionPlan?: {
		planName?: string;
		planDate?: string;
		comments?: string;
		successors?: {
		employeeDetails?: {
		firstName?: string;
		lastName?: string;
		atsRoles?: string[];
		email?: string;
		name?: string;
		userId?: string;
		atsUserGroups?: {
		userGroupId?: string;
	}[];
	};
		readiness?: string;
		comments?: string;
		rank?: number;
	}[];
	};
	/** The associated role information of the employee */
	associatedRole?: {
		primaryRoleId?: string;
		primaryRoleName?: string;
		updateAt?: number;
		roleVariantId?: string;
		roleVariantName?: string;
		externalVariantId?: string;
	};
	/** List of profile skills with assessments */
	skillDetails?: {
		evaluations?: {
		level?: number;
		proficiency?: string;
		skillGroup?: string;
		source?: string;
		assessmentProvider?: string;
		skillSubGroup?: string;
		skillGroupDescription?: string;
		skillCategory?: string;
		skillCategoryDescription?: string;
	}[];
		name?: string;
		source?: {
		name?: string;
		entityId?: string;
	};
		displayName?: string;
	}[];
	/** Metadata of the skill assessments */
	skillAssessmentMetadata?: {
		last_self_assessment_ts?: number;
		last_self_assessment_by?: number;
		last_manager_assessment_ts?: number;
		last_manager_assessment_by?: number;
	};
	/** List of employee\ */
	demandExperiences?: {
		addlJson?: Record<string, unknown>;
		department?: string;
		description?: string;
		durationMonths?: number;
		edited?: boolean;
		endTime?: number;
		experienceKey?: string;
		industry?: string;
		isCurrent?: boolean;
		isInternal?: boolean;
		location?: string;
		skills?: string[];
		startTime?: number;
		title?: string;
		userVerifiedSkills?: boolean;
		work?: string;
	}[];
	/** Temporal fields of the employee */
	temporalFields?: {
		name?: string;
		valueTimeline?: {
		startDate?: number;
		endDate?: number;
		createTs?: number;
		value?: Record<string, unknown>;
	}[];
	}[];
	/** RM user groups associated with the employee */
	rmUserGroups?: {
		userGroupId?: string;
	}[];
}

export interface EmployeeListFilters extends BaseListFilters {
	/** Filter query using predefined filter arguments documented [here](https://apidocs.eightfold.ai/v2.0/docs#the-filterquery-parameter) */
	filterQuery?: string;
	/** Any wildcard text to search in position */
	query?: string;
}

export type EmployeeList = ListEnvelope<Employee>;
export type EmployeeBatch = BatchResponse<Employee>;
