// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: entity_changelog (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface EntityChangelog {
	data?: unknown[];
	meta?: unknown;
}

export interface EntityChangelogListFilters extends BaseListFilters {
	/** Timestamp to indicate time window's start time */
	startTime: string;
	/** Timestamp to indicate time window's end time. This value should be at least 30 minutes less than the current time. */
	endTime: string;
}

export type EntityChangelogList = ListEnvelope<EntityChangelog>;
export type EntityChangelogBatch = BatchResponse<EntityChangelog>;
