// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: event (events)

import type { ListEnvelope, BatchResponse } from "./shared";

export interface Event {
	/** id */
	id?: string;
	/** Name of the event */
	name?: string;
	/** Event landing page */
	eventLandingPage?: string;
	/** active registrations */
	activeRegistrations?: string;
	/** Registration button information */
	registerButton?: {
		text?: string;
		textColor?: string;
		backgroundColor?: string;
	};
	/** Home page banner information */
	homePageBanner?: {
		image?: string;
		title?: string;
		useImage?: boolean;
	};
	/** Selected time zome */
	selectedTimezone?: string;
	/** Starting time stamp of event */
	startTimestamp?: number;
	/** Ending timestamp of event */
	endTimestamp?: number;
	/** Institution related to event */
	institution?: string;
	/** Venue of the event */
	venue?: string;
	/** Address of venue */
	address?: string;
	/** Description of event */
	description?: string;
	/** Timestamp when this event was created */
	createdAt?: number;
	/** User id which created this event */
	createdBy?: string;
	/** List of speakers */
	eventSpeakers?: string[];
	/** Event team data */
	eventTeamDataJson?: Record<string, unknown>;
	/** Event custom fields */
	eventCustomFieldsJson?: Record<string, unknown>;
	eventType?: string;
	isCancelled?: boolean;
	status?: string;
	eventLocationType?: string;
	isPublished?: boolean;
	/** Bucket of the event */
	eventBucket?: string;
	/** Parent id of the event */
	parentId?: string;
	/** Category of the event */
	eventCategory?: string;
	/** When tag of the event */
	when?: string;
}


export type EventList = ListEnvelope<Event>;
export type EventBatch = BatchResponse<Event>;
