// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: event_candidate_activity (events)

import type { ListEnvelope, BatchResponse } from "./shared";

export interface EventCandidateActivity {
	/** Event Candidate Activity Id */
	id?: string;
	/** Planned event id associated with the event activity */
	plannedEventId?: string;
	/** Position Id for the position associated to the event for some specific activity types */
	positionId?: number;
	/** Profile Id for the candidate */
	profileId?: string;
	/** Activity type for this event activity */
	activityType?: string;
	/** Activity result for this event activity */
	activityResult?: string;
	/** Subkey id for the event activity */
	subkeyId?: string;
	/** Timestamp when this event activity was created */
	createdAt?: number;
	/** Timestamp when this event activity was updated */
	updatedAt?: number;
	/** User id which created this event activity */
	createdBy?: string;
	/** User id which updated this event activity */
	updatedBy?: string;
	/** RSVP response by the candidate */
	rsvpResponse?: string;
	/** Data json for the event candidate activity */
	dataJson?: Record<string, unknown>;
}

export type EventCandidateActivityList = ListEnvelope<EventCandidateActivity>;
export type EventCandidateActivityBatch = BatchResponse<EventCandidateActivity>;
