// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: ext_demand (resource_management)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface ExtDemand {
	data?: unknown[];
	meta?: unknown;
}

export interface ExtDemandListFilters extends BaseListFilters {
	/** Filter query using predefined filter arguments documented [here](https://apidocs.eightfold.ai/v2.0/docs#the-filterquery-parameter) */
	filterQuery?: string;
	/** any wildcard text to search in external demand */
	query?: string;
	/** Include archived demands */
	includeArchived?: boolean;
}

export type ExtDemandList = ListEnvelope<ExtDemand>;
export type ExtDemandBatch = BatchResponse<ExtDemand>;
