// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: ext_ai_interview (agent_kit)

import type { ListEnvelope, BatchResponse } from "./shared";

export interface ExtAiInterview {
	[key: string]: unknown;
}


export type ExtAiInterviewList = ListEnvelope<ExtAiInterview>;
export type ExtAiInterviewBatch = BatchResponse<ExtAiInterview>;
