// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: hiring_company_hiring_company (etx)

import type { ListEnvelope, BatchResponse } from "./shared";

export interface HiringCompanyHiringCompany {
	/** Datetime when the Hiring Company was created */
	createdTs?: number;
	/** Datetime when the Hiring Company was deleted */
	deletedTs?: number;
	/** Group Id of the Hiring Company */
	hiringCompanyGroupId?: string;
	/** Reason for putting the Hiring Company on hold */
	onholdReason?: string;
	/** Status of the Hiring Company when on hold */
	onholdStatus?: string;
	/** Name of the Hiring Company */
	organizationName?: string;
	/** Primary Exchange Admin */
	primaryExchangeAdmin?: string;
	/** Reason for rejecting the Hiring Company */
	rejectReason?: string;
	/** Status of the Hiring Company */
	status?: string;
	/** User who changed the status of the Hiring Company */
	statusChangeBy?: string;
	/** Datetime when the status of the Hiring Company was changed */
	statusChangeTs?: number;
	/** Unverified information of the Hiring Company */
	unverifiedInfo?: Record<string, unknown>;
	/** Datetime when the Hiring Company was updated */
	updatedTs?: number;
	/** Verified information of the Hiring Company */
	verifiedInfo?: Record<string, unknown>;
}

export type HiringCompanyHiringCompanyList = ListEnvelope<HiringCompanyHiringCompany>;
export type HiringCompanyHiringCompanyBatch = BatchResponse<HiringCompanyHiringCompany>;
