// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: holiday (resource_management)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface Holiday {
	data?: unknown[];
	meta?: unknown;
}

export interface HolidayListFilters extends BaseListFilters {
	/** Filter on holiday type. Possible values: ['public_holiday', 'optional_holiday'] */
	holidayType?: string;
	/** Filter on holiday region */
	region?: string;
	/** The start date of the period for which you want to filter holidays */
	startDate?: string;
	/** The end date of the period for which you want to filter holidays */
	endDate?: string;
}

export type HolidayList = ListEnvelope<Holiday>;
export type HolidayBatch = BatchResponse<Holiday>;
