// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: hris_employee (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface HrisEmployee {
	/** The unique id of the Employee in the HRIS system */
	id?: string;
	/** The userId of the employee */
	userId?: string;
	/** First Name of employee */
	firstName?: string;
	/** Last Name of employee */
	lastName?: string;
	/** List of Emails of the employee comma seperated */
	email?: string;
	/** The role of the employee */
	role?: string;
	/** The job code of the employee */
	jobCode?: string;
	/** The company name of the employee */
	companyName?: string;
	/** The title of the employee */
	title?: string;
	/** The job level of the employee */
	level?: string;
	/** The location of the employee */
	location?: string;
	/** The location country of the employee */
	locationCountry?: string;
	/** The hiring date of the employee */
	hiringDate?: string;
	/** The last role change date of the employee */
	roleChangeDate?: string;
	/** The user id of the manager in HRIS system */
	managerUserId?: string;
	/** The email of the manager */
	managerEmail?: string;
	/** The full name of the manager */
	managerFullname?: string;
	/** The Business unit of the employee */
	bu?: string;
	/** The lob of the employee */
	lob?: string;
	/** The termination date of the employee */
	terminationDate?: string;
	/** The phone number of the employee */
	phone?: string;
	/** The last activity timestamp */
	lastActivityTs?: number;
	/** The system id of the HRIS system in EF */
	systemId?: string;
	/** The badges of the employee */
	badges?: {
		badgeId?: string;
		comment?: string;
		creator?: string;
		lastModifiedTs?: number;
		photoContent?: {
		content?: string;
		extension?: string;
		isBase64?: boolean;
	};
		photoUrl?: string;
		title?: string;
		userId?: string;
	}[];
	/** The base pay of the employee */
	basePay?: {
		amount?: number;
		currency?: string;
		frequency?: string;
	};
	/** The bonus given to the employee */
	bonus?: {
		amount?: number;
		currency?: string;
		frequency?: string;
	};
	/** The last review rating of the employee */
	lastReviewRating?: string;
	/** Is the employee eligible for transfer or not */
	eligibleForTransfer?: boolean;
	/** The custom info captured for the employee by custom fields */
	customInfo?: Record<string, unknown>;
	/** The criticality information of the employee */
	employeeCriticality?: {
		riskOfLoss?: string;
		impactOfLoss?: string;
	};
	/** The performance rating of the employee */
	performanceRatings?: {
		periodStartDate?: string;
		periodEndDate?: string;
		rating?: number;
		ratingLabel?: string;
		reviewType?: string;
		reviewComments?: string;
		reviewedBy?: {
		firstName?: string;
		lastName?: string;
		atsRoles?: string[];
		email?: string;
		name?: string;
		userId?: string;
		atsUserGroups?: {
		userGroupId?: string;
	}[];
	};
	}[];
	/** The criticality of the position of the employee */
	positionCriticality?: string[];
	/** The employee language proficiencies */
	languages?: {
		language?: string;
		overall?: string;
		write?: string;
		read?: string;
		speak?: string;
	}[];
	/** The succession plan of the employee */
	successionPlan?: {
		planName?: string;
		planDate?: string;
		comments?: string;
		successors?: {
		employeeDetails?: {
		firstName?: string;
		lastName?: string;
		atsRoles?: string[];
		email?: string;
		name?: string;
		userId?: string;
		atsUserGroups?: {
		userGroupId?: string;
	}[];
	};
		readiness?: string;
		comments?: string;
		rank?: number;
	}[];
	};
	/** The mobility of the employee */
	mobility?: {
		relocation?: string;
		relocationLocations?: string[];
		travel?: string;
		comments?: string;
		travelPercentageMin?: number;
		travelPercentageMax?: number;
	};
	/** The frequency of the base pay of the employee */
	basePayFrequency?: string;
	/** The currency of the base pay of the employee */
	basePayCurrency?: string;
	/** The amount of the bonus of the employee */
	bonusAmount?: number;
	/** The currency of the bonus given to the employee */
	bonusAmountCurrency?: string;
	/** The frequency of the bonus pay to the employee */
	bonusAmountFrequency?: string;
	/** The no of years the employee is in current role */
	tenureCurrentRoleYears?: number;
	/** The total tenure years of the employee */
	tenureYears?: number;
}

export interface HrisEmployeeListFilters extends BaseListFilters {
	/** Filter query using predefined filter arguments documented [here](https://apidocs.eightfold.ai/v2.0/docs#the-filterquery-parameter) */
	filterQuery?: string;
	/** Any wildcard text to search in position */
	query?: string;
}

export type HrisEmployeeList = ListEnvelope<HrisEmployee>;
export type HrisEmployeeBatch = BatchResponse<HrisEmployee>;
