// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: insight (insights)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface Insight {
	/** List of field insights */
	fieldInsights?: {
		field?: string;
		values?: {
		count?: number;
		value?: string;
	}[];
	}[];
	/** Number of Results */
	resultCount?: number;
}

export interface InsightListFilters extends BaseListFilters {
	/** Specifies the count of top <distributionFieldsLimit> values of a particular field */
	distributionFieldsLimit?: unknown;
	/** Eightfold position ID for candidates to match */
	positionMatchedFor?: string;
	/** filter query using predefined candidate field query parameters documented [here](https://apidocs.eightfold.ai/v2.0/docs#the-filterquery-parameter) */
	filterQuery?: string;
	/** any wildcard text to search in candidate data */
	query?: string;
	/** comma separated list of fields to get distributions for */
	fields?: string;
}

export type InsightList = ListEnvelope<Insight>;
export type InsightBatch = BatchResponse<Insight>;
