// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: jie (JIE)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface Jie {
	/** id of the role */
	id?: string;
	/** title of the role */
	title?: string;
	/** preferred locations for the role */
	locations?: string[];
	/** associated tags with the role, these tags are specific to a role and are generally filled in with a unique tag value. Only pre-configured tags in role_library_config:integration_config:configuration_tags are allowed */
	associatedTags?: {
		tagName?: string;
		tagValues?: string[];
	}[];
	/** display tags of the role. They may or may not be unique to a role. Only pre-configured tags in role_library_config:integration_config:display_tags are allowed */
	displayTags?: {
		tagName?: string;
		tagValues?: string[];
	}[];
	/** skill proficiencies of the role */
	skillProficiencies?: {
		level?: string;
		name?: string;
		proficiency?: number;
		skillGroupList?: {
		level?: string;
		groupName?: string;
		proficiency?: number;
		skillCategory?: string;
	}[];
	}[];
	/** LinkedIN URL\ */
	idealCandidateUrls?: string[];
	/** EF profile ids of preferred/ideal candidates for the role */
	idealCandidates?: string[];
	/** preferred experience for the role */
	experience?: {
		jobTitles?: {
		preferenceType?: string;
		value?: string;
	}[];
		companies?: {
		preferenceType?: string;
		value?: string;
	}[];
		seniorities?: string[];
		preferredYearsOfExperience?: {
		typeOfExperience?: string;
		minExperience?: number;
		maxExperience?: number;
	};
	};
	/** preferred education for the role */
	education?: {
		graduationYear?: {
		graduationStartYear?: number;
		graduationEndYear?: number;
	};
		schools?: {
		preferenceType?: string;
		value?: string;
	}[];
		degrees?: string[];
		certifications?: string[];
		degreeMajors?: string[];
	};
	/** calibration Notes for a role */
	calibrationNotes?: string;
	/** external role id for a role */
	externalId?: string;
	/** description of the role */
	roleDescription?: string;
	/** approval status of role, can be one of {} */
	approvalStatus?: string;
	/** is archival of role */
	archivalStatus?: boolean;
	/** RM user groups associated with the role. */
	rmUserGroups?: {
		userGroupId?: string;
	}[];
}

export interface JieListFilters extends BaseListFilters {
	/** Filter query using predefined filter arguments documented [here](https://apidocs.eightfold.ai/v2.0/docs#the-filterquery-parameter) */
	filterQuery?: string;
}

export type JieList = ListEnvelope<Jie>;
export type JieBatch = BatchResponse<Jie>;
