// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: offer (ats)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface Offer {
	/** job id */
	positionId?: number;
	/** unique identifier for profile */
	profileId?: string;
	/** status of the offer */
	offerStatus?: string;
	/** Offer id */
	offerId?: number;
	/** application id */
	applicationId?: number;
	/** group id */
	groupId?: string;
	/** User email who created the offer */
	createdBy?: string;
	/** Timestamp of when the offer was created */
	createdAt?: number;
	/** Timestamp of when the offer was last updated */
	updatedAt?: number;
	/** Version of the offer */
	version?: string;
	/** All versions of the offer */
	versions?: string[];
	/** Template id of the template used to create the offer */
	templateId?: number;
	/** Pay grade of the offer */
	payGradeId?: number;
	/** Base pay frequency */
	basePayFrequency?: string;
	/** Bonus pay frequency */
	bonusPayFrequency?: string;
	/** Candidate address */
	candidateAddress?: string;
	/** Currency for compensation */
	currency?: string;
	/** Joining bonus amount */
	joiningBonus?: number;
	/** Relocation bonus amount */
	relocationBonus?: number;
	/** Base salary amount */
	salaryAmount?: number;
	/** Shift allowance amount */
	shiftAllowance?: number;
	/** Stock options amount */
	stockOptionsAmount?: number;
	/** Stock options description */
	stockOptionsDescription?: string;
	/** Stock options vesting percentage */
	stockOptionsPercentageVesting?: Record<string, unknown>;
	/** Total years for stock options vesting */
	stockOptionsTotalVestingYears?: number;
	/** Stock vesting start date */
	stockVestingStartDate?: string;
	/** Type of stock options */
	stockOptionsType?: string;
	/** Stock vesting frequency */
	stockVestingFrequency?: string;
	/** Variable bonus amount */
	variableBonus?: number;
	/** Country code */
	countryCode?: string;
	/** Total compensation amount */
	totalCompensation?: number;
	/** Candidate email address */
	candidateEmail?: string;
	/** Candidate full name */
	candidateFullName?: string;
	/** Job location */
	jobLocation?: string;
	/** Job title */
	jobTitle?: string;
	/** Joining date */
	joiningDate?: string;
	/** Additional notes */
	note?: string;
	/** Visa type */
	visaType?: string;
	/** Workplace type */
	workplaceType?: string;
	/** Whether this is a people manager role */
	isPeopleManagerRole?: boolean;
	/** Whether this is a rehire */
	isRehire?: boolean;
	/** Watchers */
	watchers?: string[];
	/** Custom info */
	customInfo?: Record<string, unknown>;
	/** Offer letter details */
	offerLetter?: Record<string, unknown>;
}

export interface OfferListFilters extends BaseListFilters {
	/** Filter query using predefined filter arguments documented [here](https://apidocs.eightfold.ai/v2.0/docs#the-filterquery-parameter) */
	filterQuery?: string;
	/** any wildcard text to search in offer */
	query?: string;
	/** Whether to include attachments signed urls in the response */
	includeAttachments?: boolean;
}

export type OfferList = ListEnvelope<Offer>;
export type OfferBatch = BatchResponse<Offer>;
