// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: org_unit (t3s)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface OrgUnit {
	data?: unknown[];
	meta?: unknown;
}

export interface OrgUnitListFilters extends BaseListFilters {
	/** Filter query using predefined filter arguments documented [here](https://apidocs.eightfold.ai/v2.0/docs#the-filterquery-parameter) */
	filterQuery?: string;
	/** any wildcard text to search in org unit */
	query?: string;
}

export type OrgUnitList = ListEnvelope<OrgUnit>;
export type OrgUnitBatch = BatchResponse<OrgUnit>;
