// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: position (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface Position {
	/** ats data of the job */
	atsData?: {
		activities?: {
		activityTime?: number;
		activityType?: string;
		changeLogs?: {
		fieldName?: string;
		newValue?: string;
		prevValue?: string;
	}[];
		message?: string;
	}[];
		atsEntityId?: string;
		jobCode?: string;
		businessUnit?: string;
		company?: string;
		companyDescription?: string;
		coordinators?: {
		email?: string;
		name?: string;
	}[];
		createdAt?: number;
		createdBy?: string;
		customFields?: Record<string, unknown>;
		description?: string;
		displayJobId?: string;
		employmentType?: string;
		evergreen?: boolean;
		followers?: {
		email?: string;
		name?: string;
	}[];
		function?: string;
		hiringBand?: string;
		hiringManager?: {
		email?: string;
		name?: string;
	};
		internalPostingUrl?: string;
		jobPosts?: {
		expirationTime?: number;
		jobDescription?: string;
		postedFor?: string;
		postingId?: string;
		postingTitle?: string;
		primaryPost?: boolean;
		publishedTime?: number;
		locale?: string;
	}[];
		jobStages?: string[];
		lastUpdated?: number;
		locations?: string[];
		open?: boolean;
		openings?: {
		numOpenings?: number;
		numOpeningsFilled?: number;
		openingDetails?: {
		openingId?: string;
		status?: string;
		openedAt?: number;
		closedAt?: number;
		applicationId?: string;
		candidateId?: string;
		closeReason?: string;
	}[];
		openedAt?: number;
		closedAt?: number;
	};
		posted?: boolean;
		postedFor?: string;
		postingTitle?: string;
		postingUrl?: string;
		positionId?: number;
		questions?: {
		choices?: {
		label?: string;
		value?: string;
	}[];
		choicesV2?: {
		label?: string;
		value?: string;
		langMappingList?: {
		locale?: string;
		label?: string;
	}[];
	}[];
		required?: boolean;
		type?: string;
		questionId?: string;
		help?: string;
		question?: {
		label?: string;
		value?: string;
		langMappingList?: {
		locale?: string;
		label?: string;
	}[];
	};
	}[];
		questionnaires?: {
		questionnaireId?: string;
		questionDependencies?: {
		questionId?: string;
		choiceValue?: string;
		questionSource?: string;
		childQuestionIds?: string[];
		dependencyType?: string;
	}[];
	}[];
		recruiter?: {
		email?: string;
		name?: string;
	};
		requisitionType?: string;
		requiredSkills?: string[];
		restrictAccess?: boolean;
		skills?: string[];
		sourcers?: {
		email?: string;
		name?: string;
	}[];
		startDate?: string;
		status?: string;
		systemId?: string;
		title?: string;
		workLocationOption?: string;
		locationFlexibility?: string;
		workflowTemplateId?: string;
		isPrivate?: boolean;
		locationCity?: string;
		locationState?: string;
		locationCountry?: string;
		templateId?: number;
		orgUnits?: Record<string, unknown>;
		atsUserGroups?: {
		userGroupId?: string;
	}[];
		hiringTeam?: {
		role?: string;
		roleKey?: string;
		name?: string;
		email?: string;
	}[];
	};
	/** calibration data of the job */
	calibrationData?: {
		companies?: string[];
		diversity?: string[];
		educationLevel?: string[];
		flags?: string[];
		graduationYear?: string;
		idealCandidateUrls?: string[];
		idealCandidates?: string[];
		locations?: string[];
		maxExperience?: number;
		minExperience?: number;
		notes?: string;
		relocation?: string[];
		schools?: string[];
		seniorities?: string[];
		skills?: string[];
		titles?: string[];
		workCategories?: string[];
		skillProficiencies?: {
		level?: string;
		name?: string;
		proficiency?: number;
		skillGroupList?: {
		level?: string;
		groupName?: string;
		proficiency?: number;
		skillCategory?: string;
	}[];
	}[];
	};
	/** if the position is confidential or not */
	confidential?: boolean;
	/** source of the job */
	createdBy?: string;
	/** all the followers of the position */
	followers?: string[];
	/** group id */
	groupId?: string;
	/** Hiring Manager */
	hiringManager?: {
		email?: string;
		name?: string;
	};
	/** Detailed Job Description in a text format */
	jobDescription?: string;
	/** Title of the Position */
	name?: string;
	/** if the position is open or not */
	open?: boolean;
	/** display job id */
	positionDisplayId?: string;
	/** job id */
	positionId?: number;
	/** Recruiter */
	recruiter?: {
		email?: string;
		name?: string;
	};
	/** role associated with the position */
	role?: {
		templates?: {
		name?: string;
		id?: number;
	}[];
		name?: string;
	};
	/** system id */
	systemId?: string;
	/** User who confirmed the calibration */
	calibrationConfirmedBy?: string;
	/** Confirmed timestamp for the calibration */
	calibrationConfirmedAt?: number;
	/** Creation timestamp in epoch format */
	createdAt?: number;
}

export interface PositionListFilters extends BaseListFilters {
	/** unique identifier in the ATS system */
	atsJobId?: string;
	/** Filter query using predefined filter arguments documented [here](https://apidocs.eightfold.ai/v2.0/docs#the-filterquery-parameter) */
	filterQuery?: string;
	/** any wildcard text to search in position */
	query?: string;
	/** show archived positions */
	includeArchived?: boolean;
}

export type PositionList = ListEnvelope<Position>;
export type PositionBatch = BatchResponse<Position>;
