// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: profile_entity_application (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface ProfileEntityApplication {
	/** object id of the profile application */
	id?: number;
	/** application id of profile application */
	applicationId?: number;
	/** application timestamp of profile application */
	applicationTime?: number;
	/** application answers of candidate application */
	applicationAnswers?: {
		answer?: string;
		question?: string;
		questionId?: string;
	}[];
	/** candidate id of profile application */
	candidateId?: string;
	/** current stage of profile application */
	currentStage?: string;
	groupId?: string;
	/** last modified timestamp of profile application */
	lastModifiedTime?: number;
	/** entity id of profile application */
	entityId?: number;
	/** namespace of profile application */
	namespace?: string;
	stage?: string;
	/** comment added during stage advance */
	comment?: string;
	/** user who advanced the stage */
	actionUser?: {
		email?: string;
		name?: string;
	};
	/** custom info for the application */
	customInfo?: Record<string, unknown>;
	/** profile id of candidate */
	profileId?: number;
	/** status of the application */
	status?: string;
}

export interface ProfileEntityApplicationListFilters extends BaseListFilters {
	/** Filter on entity id associated with the application */
	entityId?: string;
}

export type ProfileEntityApplicationList = ListEnvelope<ProfileEntityApplication>;
export type ProfileEntityApplicationBatch = BatchResponse<ProfileEntityApplication>;
