// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: profile_tag (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface ProfileTag {
	/** Created time of candidate Tag */
	createdTime?: number;
	/** creator email of candidate Tag */
	creatorEmail?: string;
	/** group id */
	groupId?: string;
	/** Tag id of candidate */
	id?: string;
	/** position id */
	positionId?: string;
	/** candidate profile Id */
	profileId?: string;
	/** candidate Tag */
	tag?: string;
	/** Tag subtype */
	tagSubtype?: string;
	/** Type of candidate Tag */
	tagType?: string;
	/** url */
	url?: string;
}

export interface ProfileTagListFilters extends BaseListFilters {
	/** Limit on the total number of search results, defaults to 100 */
	queryLimit?: string;
	/** Filter on creator email of Profile Tag */
	creatorEmail?: string;
	/** Filter on profile id of the candidate */
	profileId?: string;
	/** Filter on position id associated with the tag */
	positionId?: string;
}

export type ProfileTagList = ListEnvelope<ProfileTag>;
export type ProfileTagBatch = BatchResponse<ProfileTag>;
