// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: profile_application (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface ProfileApplication {
	/** application answers of candidate application */
	applicationAnswers?: {
		answer?: string;
		question?: string;
		questionId?: string;
	}[];
	/** object id of the profile application */
	id?: string;
	/** application id of candidate application */
	applicationId?: string;
	/** application status of candidate application */
	applicationStatus?: string;
	/** application time of candidate application */
	applicationTime?: number;
	/** name of candidate application */
	atsJobId?: string;
	/** candidate id of candidate application */
	candidateId?: string;
	/** profile id of candidate application */
	profileId?: number;
	/** Current stage of candidate application */
	currentStage?: string;
	/** Latest feedback of candidate application */
	feedback?: {
		feedbackId?: number;
		feedbackEncId?: string;
		feedbackResponse?: {
		overallFeedback?: {
		questionId?: number;
		answer?: Record<string, unknown>;
		label?: string;
		comment?: string;
	};
	};
		feedbackType?: string;
		status?: string;
		reviewer?: {
		fullName?: string;
		email?: string;
		redirectEmail?: string;
		domain?: string;
	};
		requester?: {
		fullName?: string;
		email?: string;
		redirectEmail?: string;
		domain?: string;
	};
		reviewerEmail?: string;
		requesterEmail?: string;
		matchingData?: {
		indeterminable?: number;
		relevantScoreTypeVal?: number;
		score?: number;
		scoreRaw?: number;
		scoreType?: string;
		topMatches?: string[];
	}[];
		position?: {
		atsData?: {
		activities?: {
		activityTime?: number;
		activityType?: string;
		changeLogs?: {
		fieldName?: string;
		newValue?: string;
		prevValue?: string;
	}[];
		message?: string;
	}[];
		atsEntityId?: string;
		jobCode?: string;
		businessUnit?: string;
		company?: string;
		companyDescription?: string;
		coordinators?: {
		email?: string;
		name?: string;
	}[];
		createdAt?: number;
		createdBy?: string;
		customFields?: Record<string, unknown>;
		description?: string;
		displayJobId?: string;
		employmentType?: string;
		evergreen?: boolean;
		followers?: {
		email?: string;
		name?: string;
	}[];
		function?: string;
		hiringBand?: string;
		hiringManager?: {
		email?: string;
		name?: string;
	};
		internalPostingUrl?: string;
		jobPosts?: {
		expirationTime?: number;
		jobDescription?: string;
		postedFor?: string;
		postingId?: string;
		postingTitle?: string;
		primaryPost?: boolean;
		publishedTime?: number;
		locale?: string;
	}[];
		jobStages?: string[];
		lastUpdated?: number;
		locations?: string[];
		open?: boolean;
		openings?: {
		numOpenings?: number;
		numOpeningsFilled?: number;
		openingDetails?: {
		openingId?: string;
		status?: string;
		openedAt?: number;
		closedAt?: number;
		applicationId?: string;
		candidateId?: string;
		closeReason?: string;
	}[];
		openedAt?: number;
		closedAt?: number;
	};
		posted?: boolean;
		postedFor?: string;
		postingTitle?: string;
		postingUrl?: string;
		positionId?: number;
		questions?: {
		choices?: {
		label?: string;
		value?: string;
	}[];
		choicesV2?: {
		label?: string;
		value?: string;
		langMappingList?: {
		locale?: string;
		label?: string;
	}[];
	}[];
		required?: boolean;
		type?: string;
		questionId?: string;
		help?: string;
		question?: {
		label?: string;
		value?: string;
		langMappingList?: {
		locale?: string;
		label?: string;
	}[];
	};
	}[];
		questionnaires?: {
		questionnaireId?: string;
		questionDependencies?: {
		questionId?: string;
		choiceValue?: string;
		questionSource?: string;
		childQuestionIds?: string[];
		dependencyType?: string;
	}[];
	}[];
		recruiter?: {
		email?: string;
		name?: string;
	};
		requisitionType?: string;
		requiredSkills?: string[];
		restrictAccess?: boolean;
		skills?: string[];
		sourcers?: {
		email?: string;
		name?: string;
	}[];
		startDate?: string;
		status?: string;
		systemId?: string;
		title?: string;
		workLocationOption?: string;
		locationFlexibility?: string;
		workflowTemplateId?: string;
		isPrivate?: boolean;
		locationCity?: string;
		locationState?: string;
		locationCountry?: string;
		templateId?: number;
		orgUnits?: Record<string, unknown>;
		atsUserGroups?: {
		userGroupId?: string;
	}[];
		hiringTeam?: {
		role?: string;
		roleKey?: string;
		name?: string;
		email?: string;
	}[];
	};
		calibrationData?: {
		companies?: string[];
		diversity?: string[];
		educationLevel?: string[];
		flags?: string[];
		graduationYear?: string;
		idealCandidateUrls?: string[];
		idealCandidates?: string[];
		locations?: string[];
		maxExperience?: number;
		minExperience?: number;
		notes?: string;
		relocation?: string[];
		schools?: string[];
		seniorities?: string[];
		skills?: string[];
		titles?: string[];
		workCategories?: string[];
		skillProficiencies?: {
		level?: string;
		name?: string;
		proficiency?: number;
		skillGroupList?: {
		level?: string;
		groupName?: string;
		proficiency?: number;
		skillCategory?: string;
	}[];
	}[];
	};
		confidential?: boolean;
		createdBy?: string;
		followers?: string[];
		groupId?: string;
		hiringManager?: {
		email?: string;
		name?: string;
	};
		jobDescription?: string;
		name?: string;
		open?: boolean;
		positionDisplayId?: string;
		positionId?: number;
		recruiter?: {
		email?: string;
		name?: string;
	};
		role?: {
		templates?: {
		name?: string;
		id?: number;
	}[];
		name?: string;
	};
		systemId?: string;
		calibrationConfirmedBy?: string;
		calibrationConfirmedAt?: number;
		createdAt?: number;
	};
		positionId?: string;
		profileId?: number;
		feedbackUrl?: string;
		viewFeedbackUrl?: string;
		reminderCount?: number;
		communityId?: number;
		plannedEventId?: number;
		plannedEvent?: {
		id?: string;
		name?: string;
		eventLandingPage?: string;
		activeRegistrations?: string;
		registerButton?: {
		text?: string;
		textColor?: string;
		backgroundColor?: string;
	};
		homePageBanner?: {
		image?: string;
		title?: string;
		useImage?: boolean;
	};
		selectedTimezone?: string;
		startTimestamp?: number;
		endTimestamp?: number;
		institution?: string;
		venue?: string;
		address?: string;
		description?: string;
		createdAt?: number;
		createdBy?: string;
		eventSpeakers?: string[];
		eventTeamDataJson?: Record<string, unknown>;
		eventCustomFieldsJson?: Record<string, unknown>;
		eventType?: string;
		isCancelled?: boolean;
		status?: string;
		eventLocationType?: string;
		isPublished?: boolean;
		eventBucket?: string;
		parentId?: string;
		eventCategory?: string;
		when?: string;
	};
		sharedFeedbackMessageId?: number;
		archiveFlag?: boolean;
		followUpEnabled?: boolean;
		requestedAt?: number;
		submittedAt?: number;
		feedbackJson?: Record<string, unknown>;
		feedbackTemplateId?: number;
		feedbackTemplateName?: string;
		userCalendarEventId?: number;
		createdAt?: string;
	};
	groupId?: string;
	/** Is application a referral one */
	isReferral?: boolean;
	/** Is application internal one */
	isInternal?: boolean;
	/** Last Modified time stamp of candidate application */
	lastModifiedTime?: number;
	matchingData?: {
		indeterminable?: number;
		relevantScoreTypeVal?: number;
		score?: number;
		scoreRaw?: number;
		scoreType?: string;
		topMatches?: string[];
	}[];
	position?: {
		atsData?: {
		activities?: {
		activityTime?: number;
		activityType?: string;
		changeLogs?: {
		fieldName?: string;
		newValue?: string;
		prevValue?: string;
	}[];
		message?: string;
	}[];
		atsEntityId?: string;
		jobCode?: string;
		businessUnit?: string;
		company?: string;
		companyDescription?: string;
		coordinators?: {
		email?: string;
		name?: string;
	}[];
		createdAt?: number;
		createdBy?: string;
		customFields?: Record<string, unknown>;
		description?: string;
		displayJobId?: string;
		employmentType?: string;
		evergreen?: boolean;
		followers?: {
		email?: string;
		name?: string;
	}[];
		function?: string;
		hiringBand?: string;
		hiringManager?: {
		email?: string;
		name?: string;
	};
		internalPostingUrl?: string;
		jobPosts?: {
		expirationTime?: number;
		jobDescription?: string;
		postedFor?: string;
		postingId?: string;
		postingTitle?: string;
		primaryPost?: boolean;
		publishedTime?: number;
		locale?: string;
	}[];
		jobStages?: string[];
		lastUpdated?: number;
		locations?: string[];
		open?: boolean;
		openings?: {
		numOpenings?: number;
		numOpeningsFilled?: number;
		openingDetails?: {
		openingId?: string;
		status?: string;
		openedAt?: number;
		closedAt?: number;
		applicationId?: string;
		candidateId?: string;
		closeReason?: string;
	}[];
		openedAt?: number;
		closedAt?: number;
	};
		posted?: boolean;
		postedFor?: string;
		postingTitle?: string;
		postingUrl?: string;
		positionId?: number;
		questions?: {
		choices?: {
		label?: string;
		value?: string;
	}[];
		choicesV2?: {
		label?: string;
		value?: string;
		langMappingList?: {
		locale?: string;
		label?: string;
	}[];
	}[];
		required?: boolean;
		type?: string;
		questionId?: string;
		help?: string;
		question?: {
		label?: string;
		value?: string;
		langMappingList?: {
		locale?: string;
		label?: string;
	}[];
	};
	}[];
		questionnaires?: {
		questionnaireId?: string;
		questionDependencies?: {
		questionId?: string;
		choiceValue?: string;
		questionSource?: string;
		childQuestionIds?: string[];
		dependencyType?: string;
	}[];
	}[];
		recruiter?: {
		email?: string;
		name?: string;
	};
		requisitionType?: string;
		requiredSkills?: string[];
		restrictAccess?: boolean;
		skills?: string[];
		sourcers?: {
		email?: string;
		name?: string;
	}[];
		startDate?: string;
		status?: string;
		systemId?: string;
		title?: string;
		workLocationOption?: string;
		locationFlexibility?: string;
		workflowTemplateId?: string;
		isPrivate?: boolean;
		locationCity?: string;
		locationState?: string;
		locationCountry?: string;
		templateId?: number;
		orgUnits?: Record<string, unknown>;
		atsUserGroups?: {
		userGroupId?: string;
	}[];
		hiringTeam?: {
		role?: string;
		roleKey?: string;
		name?: string;
		email?: string;
	}[];
	};
		calibrationData?: {
		companies?: string[];
		diversity?: string[];
		educationLevel?: string[];
		flags?: string[];
		graduationYear?: string;
		idealCandidateUrls?: string[];
		idealCandidates?: string[];
		locations?: string[];
		maxExperience?: number;
		minExperience?: number;
		notes?: string;
		relocation?: string[];
		schools?: string[];
		seniorities?: string[];
		skills?: string[];
		titles?: string[];
		workCategories?: string[];
		skillProficiencies?: {
		level?: string;
		name?: string;
		proficiency?: number;
		skillGroupList?: {
		level?: string;
		groupName?: string;
		proficiency?: number;
		skillCategory?: string;
	}[];
	}[];
	};
		confidential?: boolean;
		createdBy?: string;
		followers?: string[];
		groupId?: string;
		hiringManager?: {
		email?: string;
		name?: string;
	};
		jobDescription?: string;
		name?: string;
		open?: boolean;
		positionDisplayId?: string;
		positionId?: number;
		recruiter?: {
		email?: string;
		name?: string;
	};
		role?: {
		templates?: {
		name?: string;
		id?: number;
	}[];
		name?: string;
	};
		systemId?: string;
		calibrationConfirmedBy?: string;
		calibrationConfirmedAt?: number;
		createdAt?: number;
	};
	/** Position id of candidate application */
	positionId?: number;
	/** Position title of candidate application */
	positionTitle?: string;
	/** referee email for referred candidate application */
	refereeEmail?: string;
	/** source name of candidate application */
	sourceName?: string;
	/** source type of candidate application */
	sourceType?: string;
	stage?: string;
	/** Comment added during stage advance */
	comment?: string;
	/** User who advanced the stage */
	actionUser?: {
		email?: string;
		name?: string;
	};
	/** visa status of candidate application */
	visaStatus?: string;
	/** custom info for the application */
	customInfo?: Record<string, unknown>;
	/** utm source for the application */
	utm_source?: string;
	/** utm campaign for the application */
	utm_campaign?: string;
	/** Is candidate in talent network */
	isInTalentNetwork?: boolean;
	/** Is application from career site */
	isCareerSite?: boolean;
}

export interface ProfileApplicationListFilters extends BaseListFilters {
	/** Limit on the total number of search results, defaults to 100 */
	queryLimit?: string;
	/** Filter on application id */
	applicationId?: string;
	/** Filter on profile id of the candidate */
	profileId?: string;
	/** Filter on position id associated with the application */
	positionId?: string;
	/** Filter on ats job id */
	atsJobId?: string;
	/** Filter on status of the application */
	applicationStatus?: string;
	/** Filter on application stage */
	stage?: string;
}

export type ProfileApplicationList = ListEnvelope<ProfileApplication>;
export type ProfileApplicationBatch = BatchResponse<ProfileApplication>;
