// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: profile_note (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface ProfileNote {
	/** created time of candidate in datetime format */
	createdTime?: number;
	/** creator email of candidate */
	creatorEmail?: string;
	/** Note of candidate */
	note?: string;
	/** Note type of candidate */
	noteType?: string;
	/** Position id associated with the note */
	positionId?: string;
	/** Note id of candidate */
	id?: string;
	/** Profile id of candidate */
	profileId?: string;
}

export interface ProfileNoteListFilters extends BaseListFilters {
	/** Limit on the total number of search results, defaults to 100 */
	queryLimit?: string;
	/** Creator user id to filter on */
	creatorEmail?: string;
	/** profile id to filter on */
	profileId?: string;
}

export type ProfileNoteList = ListEnvelope<ProfileNote>;
export type ProfileNoteBatch = BatchResponse<ProfileNote>;
