// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: profile (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface Profile {
	/** role id associated with the profile */
	roleId?: string;
	/** List of profile skills */
	skills?: {
		evaluations?: {
		level?: number;
		proficiency?: string;
		skillGroup?: string;
		source?: string;
		assessmentProvider?: string;
		skillSubGroup?: string;
		skillGroupDescription?: string;
		skillCategory?: string;
		skillCategoryDescription?: string;
	}[];
		name?: string;
		source?: {
		name?: string;
		entityId?: string;
	};
		displayName?: string;
	}[];
	/** List of profile skill goals */
	skillGoals?: {
		goalType?: string;
		skill?: string;
	}[];
	/** Employee Information */
	employeeInfo?: {
		relocationPreferences?: {
		comments?: string;
		externalKey?: string;
		relocation?: string;
		relocationLocations?: string[];
		travel?: string;
		travelPercentageMin?: number;
		travelPercentageMax?: number;
	};
		performanceManagement?: {
		performanceRatings?: {
		performancePeriodStartDate?: string;
		performancePeriodEndDate?: string;
		rating?: number;
		ratingLabel?: string;
		reviewType?: string;
		reviewComments?: string[];
		reviewedBy?: {
		profileId?: string;
		email?: string;
	};
	}[];
		promotionReadiness?: {
		readiness?: string;
		managerProfileId?: string;
	};
	};
		successionPlan?: {
		successionPlanId?: string;
		successionPlanRole?: string;
		leaderWithoutPathForward?: string;
		successors?: {
		successorProfileId?: string;
		successorReadiness?: string;
	}[];
		successionPlanNotes?: {
		noteType?: string;
		content?: string;
		managerName?: string;
		managerProfileId?: string;
		noteId?: string;
		status?: string;
	}[];
		successionPlanMetrics?: {
		readiness?: Record<string, unknown>;
	};
	};
		employeeId?: string;
	};
	/** Additional section defined by the customer */
	additionalSections?: Record<string, unknown>;
	/** The schema for the staged profile data */
	profileStagedSections?: {
		awards?: Record<string, unknown>;
		education?: Record<string, unknown>;
		endorsements?: Record<string, unknown>;
		experiences?: Record<string, unknown>;
		patents?: Record<string, unknown>;
		projects?: Record<string, unknown>;
		publications?: Record<string, unknown>;
		skills?: Record<string, unknown>;
		certificates?: Record<string, unknown>;
		languageProficiencies?: Record<string, unknown>;
		courses?: Record<string, unknown>;
	};
	/** Group memberships and affiliations to internal groups */
	internalGroupAffiliation?: {
		internalGroup?: string;
		description?: string;
		title?: string;
		positionType?: string;
		startTs?: number;
		endTs?: number;
		isCurrent?: boolean;
	}[];
	/** List of candidate\ */
	demandExperiences?: {
		addlJson?: Record<string, unknown>;
		department?: string;
		description?: string;
		durationMonths?: number;
		edited?: boolean;
		endTime?: number;
		experienceKey?: string;
		industry?: string;
		isCurrent?: boolean;
		isInternal?: boolean;
		location?: string;
		skills?: string[];
		startTime?: number;
		title?: string;
		userVerifiedSkills?: boolean;
		work?: string;
	}[];
	/** Flag indicating whether the candidate profile is confidential. Setting this to true will add the Confidential tag to the profile. */
	isConfidential?: boolean;
}

export interface ProfileListFilters extends BaseListFilters {
	/** Unique identifier in the ATS system */
	atsCandidateId?: string;
	/** Comma separated list of encoded profile ids */
	profileIds?: string;
	/** Filter query using predefined filter arguments documented [here](https://apidocs.eightfold.ai/v2.0/docs#the-filterquery-parameter) */
	filterQuery?: string;
	/** Any wildcard text to search in position */
	query?: string;
}

export type ProfileList = ListEnvelope<Profile>;
export type ProfileBatch = BatchResponse<Profile>;
