// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: profile_event_calendar (events)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface ProfileEventCalendar {
	data?: unknown[];
	meta?: unknown;
}

export interface ProfileEventCalendarListFilters extends BaseListFilters {
	/** Limit on the total number of search results, defaults to 100 */
	queryLimit?: string;
	/** Filter on planned event id for the event acitivities */
	plannedEventId?: string;
	/** Filter on profile id of the candidate */
	profileId?: string;
	/** Filter on position id associated with the event activity */
	positionId?: string;
	/** Filter on type of activity */
	activityType?: string;
	/** Filter on subkey id of the event activity */
	subkeyId?: string;
	/** Filter on user id who created the event */
	createdBy?: string;
}

export type ProfileEventCalendarList = ListEnvelope<ProfileEventCalendar>;
export type ProfileEventCalendarBatch = BatchResponse<ProfileEventCalendar>;
