// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: profile_feedback (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface ProfileFeedback {
	/** ID of the ProfileFeedback */
	feedbackId?: number;
	/** Encoded ID of the ProfileFeedback */
	feedbackEncId?: string;
	/** Received feedback\ */
	feedbackResponse?: {
		overallFeedback?: {
		questionId?: number;
		answer?: Record<string, unknown>;
		label?: string;
		comment?: string;
	};
	};
	/** type of the feedback */
	feedbackType?: string;
	/** status of the feedback */
	status?: string;
	/** Reviewer of the ProfileFeedback */
	reviewer?: {
		fullName?: string;
		email?: string;
		redirectEmail?: string;
		domain?: string;
	};
	/** Requester of the ProfileFeedback */
	requester?: {
		fullName?: string;
		email?: string;
		redirectEmail?: string;
		domain?: string;
	};
	/** Email of reviewer of the ProfileFeedback */
	reviewerEmail?: string;
	/** Email of requester of the ProfileFeedback */
	requesterEmail?: string;
	/** Application matching information */
	matchingData?: {
		indeterminable?: number;
		relevantScoreTypeVal?: number;
		score?: number;
		scoreRaw?: number;
		scoreType?: string;
		topMatches?: string[];
	}[];
	/** Position for which feedback was given */
	position?: {
		atsData?: {
		activities?: {
		activityTime?: number;
		activityType?: string;
		changeLogs?: {
		fieldName?: string;
		newValue?: string;
		prevValue?: string;
	}[];
		message?: string;
	}[];
		atsEntityId?: string;
		jobCode?: string;
		businessUnit?: string;
		company?: string;
		companyDescription?: string;
		coordinators?: {
		email?: string;
		name?: string;
	}[];
		createdAt?: number;
		createdBy?: string;
		customFields?: Record<string, unknown>;
		description?: string;
		displayJobId?: string;
		employmentType?: string;
		evergreen?: boolean;
		followers?: {
		email?: string;
		name?: string;
	}[];
		function?: string;
		hiringBand?: string;
		hiringManager?: {
		email?: string;
		name?: string;
	};
		internalPostingUrl?: string;
		jobPosts?: {
		expirationTime?: number;
		jobDescription?: string;
		postedFor?: string;
		postingId?: string;
		postingTitle?: string;
		primaryPost?: boolean;
		publishedTime?: number;
		locale?: string;
	}[];
		jobStages?: string[];
		lastUpdated?: number;
		locations?: string[];
		open?: boolean;
		openings?: {
		numOpenings?: number;
		numOpeningsFilled?: number;
		openingDetails?: {
		openingId?: string;
		status?: string;
		openedAt?: number;
		closedAt?: number;
		applicationId?: string;
		candidateId?: string;
		closeReason?: string;
	}[];
		openedAt?: number;
		closedAt?: number;
	};
		posted?: boolean;
		postedFor?: string;
		postingTitle?: string;
		postingUrl?: string;
		positionId?: number;
		questions?: {
		choices?: {
		label?: string;
		value?: string;
	}[];
		choicesV2?: {
		label?: string;
		value?: string;
		langMappingList?: {
		locale?: string;
		label?: string;
	}[];
	}[];
		required?: boolean;
		type?: string;
		questionId?: string;
		help?: string;
		question?: {
		label?: string;
		value?: string;
		langMappingList?: {
		locale?: string;
		label?: string;
	}[];
	};
	}[];
		questionnaires?: {
		questionnaireId?: string;
		questionDependencies?: {
		questionId?: string;
		choiceValue?: string;
		questionSource?: string;
		childQuestionIds?: string[];
		dependencyType?: string;
	}[];
	}[];
		recruiter?: {
		email?: string;
		name?: string;
	};
		requisitionType?: string;
		requiredSkills?: string[];
		restrictAccess?: boolean;
		skills?: string[];
		sourcers?: {
		email?: string;
		name?: string;
	}[];
		startDate?: string;
		status?: string;
		systemId?: string;
		title?: string;
		workLocationOption?: string;
		locationFlexibility?: string;
		workflowTemplateId?: string;
		isPrivate?: boolean;
		locationCity?: string;
		locationState?: string;
		locationCountry?: string;
		templateId?: number;
		orgUnits?: Record<string, unknown>;
		atsUserGroups?: {
		userGroupId?: string;
	}[];
		hiringTeam?: {
		role?: string;
		roleKey?: string;
		name?: string;
		email?: string;
	}[];
	};
		calibrationData?: {
		companies?: string[];
		diversity?: string[];
		educationLevel?: string[];
		flags?: string[];
		graduationYear?: string;
		idealCandidateUrls?: string[];
		idealCandidates?: string[];
		locations?: string[];
		maxExperience?: number;
		minExperience?: number;
		notes?: string;
		relocation?: string[];
		schools?: string[];
		seniorities?: string[];
		skills?: string[];
		titles?: string[];
		workCategories?: string[];
		skillProficiencies?: {
		level?: string;
		name?: string;
		proficiency?: number;
		skillGroupList?: {
		level?: string;
		groupName?: string;
		proficiency?: number;
		skillCategory?: string;
	}[];
	}[];
	};
		confidential?: boolean;
		createdBy?: string;
		followers?: string[];
		groupId?: string;
		hiringManager?: {
		email?: string;
		name?: string;
	};
		jobDescription?: string;
		name?: string;
		open?: boolean;
		positionDisplayId?: string;
		positionId?: number;
		recruiter?: {
		email?: string;
		name?: string;
	};
		role?: {
		templates?: {
		name?: string;
		id?: number;
	}[];
		name?: string;
	};
		systemId?: string;
		calibrationConfirmedBy?: string;
		calibrationConfirmedAt?: number;
		createdAt?: number;
	};
	/** Position ID for which feedback was given */
	positionId?: string;
	/** Profile ID associated with the profile feedback */
	profileId?: number;
	/** URL to provide feedback */
	feedbackUrl?: string;
	/** URL to view feedback */
	viewFeedbackUrl?: string;
	/** Number of reminders sent */
	reminderCount?: number;
	/** Community Id for candidate source */
	communityId?: number;
	/** Planned event id for candidate source */
	plannedEventId?: number;
	/** Planned event for candidate source */
	plannedEvent?: {
		id?: string;
		name?: string;
		eventLandingPage?: string;
		activeRegistrations?: string;
		registerButton?: {
		text?: string;
		textColor?: string;
		backgroundColor?: string;
	};
		homePageBanner?: {
		image?: string;
		title?: string;
		useImage?: boolean;
	};
		selectedTimezone?: string;
		startTimestamp?: number;
		endTimestamp?: number;
		institution?: string;
		venue?: string;
		address?: string;
		description?: string;
		createdAt?: number;
		createdBy?: string;
		eventSpeakers?: string[];
		eventTeamDataJson?: Record<string, unknown>;
		eventCustomFieldsJson?: Record<string, unknown>;
		eventType?: string;
		isCancelled?: boolean;
		status?: string;
		eventLocationType?: string;
		isPublished?: boolean;
		eventBucket?: string;
		parentId?: string;
		eventCategory?: string;
		when?: string;
	};
	/** Message Id for shared feedback */
	sharedFeedbackMessageId?: number;
	/** Denotes if the feedback is archived or not */
	archiveFlag?: boolean;
	/** Denotes if the feedback follow up is enabled or not */
	followUpEnabled?: boolean;
	/** Timestamp when the feedback was requested */
	requestedAt?: number;
	/** Timestamp when the feedback was first submitted */
	submittedAt?: number;
	/** Feedback JSON */
	feedbackJson?: Record<string, unknown>;
	/** Feedback template ID */
	feedbackTemplateId?: number;
	/** Feedback template name */
	feedbackTemplateName?: string;
	/** User calendar event id */
	userCalendarEventId?: number;
	/** Datetime when this feedback was created */
	createdAt?: string;
}

export interface ProfileFeedbackListFilters extends BaseListFilters {
	/** Limit on the total number of search results, defaults to 100 */
	queryLimit?: string;
	/** Filter on type of the feedback */
	feedbackType?: string;
	/** Filter on profile id of the candidate */
	profileId?: string;
	/** Filter on position id associated with the feedback */
	positionId?: string;
	/** Filter on requester email of feedback */
	requesterEmail?: string;
	/** Filter on reviewer email of feedback */
	reviewerEmail?: string;
	/** Filter on status of the feedback */
	status?: string;
}

export type ProfileFeedbackList = ListEnvelope<ProfileFeedback>;
export type ProfileFeedbackBatch = BatchResponse<ProfileFeedback>;
