// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: resource_management (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface ResourceManagement {
	/** Comment content in text (HTML) format */
	comment?: string;
	/** Comment ID */
	commentId?: number;
	/** Comment creation timestamp */
	createdAt?: number;
	/** Email of the user who created the comment */
	createdBy?: string;
	/** ID of the entity the comment is associated with */
	entityId?: number;
	/** Type of entity the comment is associated with */
	entityType?: string;
	/** Group ID */
	groupId?: string;
	/** Whether the comment is private */
	isPrivate?: boolean;
	/** ID of the parent comment */
	parentId?: number;
	/** Comment update timestamp */
	updatedAt?: number;
}

export interface ResourceManagementListFilters extends BaseListFilters {
	/** Type of entity to filter comments by. Supported entity types: demand */
	entityType: string;
	/** ID of entity to filter comments by */
	entityId: unknown;
}

export type ResourceManagementList = ListEnvelope<ResourceManagement>;
export type ResourceManagementBatch = BatchResponse<ResourceManagement>;
