// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: succession_plan (careerhub)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface SuccessionPlan {
	/** ATS/HRIS position ID associated with the plan */
	entityId?: string;
	/** Eightfold position ID associated with the succession plan */
	positionId?: number;
	/** Name of the succession plan */
	planName?: string;
	/** Timestamp representing creation date and time of the succession plan */
	createdAt?: number;
	/** Timestamp representing the updation date and time of the succession plan */
	updatedAt?: number;
	/** Type of the succession plan Ex. either "position" or "role" (only honored for POST) */
	planType?: string;
	/** Description of the succession plan */
	description?: string;
	/** Incumbents of the succession plan */
	incumbents?: {
		employeeId?: string;
		profileId?: number;
		externalJobId?: string;
	}[];
	/** Successors of the succession plan */
	successors?: {
		profileId?: number;
		matchScores?: {
		matchType?: string;
		score?: number;
		rawScore?: number;
		topMatches?: string[];
	}[];
		employeeId?: string;
		state?: string;
		order?: number;
		createdAt?: number;
		updatedAt?: number;
	}[];
	/** Eightfold role ID associated with the succession plan */
	associatedRoleId?: string;
	/** External job code of the incumbent(s) */
	jobCode?: string;
	/** Caretaker profile IDs of the succession plan */
	caretakers?: {
		employeeId?: string;
		profileId?: number;
		createdAt?: number;
		updatedAt?: number;
	}[];
	/** Metric fields highlighting key aspects of the succession plan */
	metricFields?: {
		femalePercentage?: number;
		diverseEthnicityPercentage?: number;
		pipelineStrength?: string;
		insightTag?: string[];
	};
	/** Criticality tags of the succession plan that is associated with the position held by the incumbent */
	positionCriticalityTags?: string[];
	/** Criticality tags of the role that is associated with the position held by the incumbent */
	roleCriticalityTags?: string[];
}

export interface SuccessionPlanListFilters extends BaseListFilters {
	/** This specifies list of incumbent profile IDs. If this is given, only plans that have incumbents who match the specified profile IDs are returned. The format should be comma-separated values with or without spaces (ex. 1000,2000, 3000). */
	incumbentIds?: string;
	/** Wildcard text used when searching for the results */
	query?: string;
}

export type SuccessionPlanList = ListEnvelope<SuccessionPlan>;
export type SuccessionPlanBatch = BatchResponse<SuccessionPlan>;
