// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: talent_pool (smartapply)

import type { ListEnvelope, BatchResponse } from "./shared";

export interface TalentPool {
	/** Subscribed for emails */
	emailSubscription?: boolean;
	/** Response message for Joining Talent Pool */
	message?: string;
	/** Profile Id to be added in the Talent Pool */
	profileId?: string;
	/** Tags of profile for Talent Pool */
	tags?: string[];
}

export type TalentPoolList = ListEnvelope<TalentPool>;
export type TalentPoolBatch = BatchResponse<TalentPool>;
