// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: upskill_plan_assignment (careerhub)

import type { ListEnvelope, BatchResponse } from "./shared";

export interface UpskillPlanAssignment {
	/** Assignment id (profile_data primary key) */
	id?: number;
	/** Assignee profile id */
	profileId?: number;
	/** Tenant group id */
	groupId?: string;
	/** Template plan id this assignment was cloned from */
	parentPlanId?: number;
	/** Created timestamp (epoch seconds) */
	createdAt?: number;
	/** Updated timestamp (epoch seconds) */
	updatedAt?: number;
	/** invited | in_progress | completed | archived */
	planStatus?: string;
	/** Start date (epoch seconds) */
	startDate?: number;
	/** Target completion date (epoch seconds) */
	targetDate?: number;
	/** Last progress timestamp (epoch seconds, system-set) */
	lastProgressTs?: number;
	/** Last notification timestamp (epoch seconds, system-set) */
	lastNotifiedTs?: number;
	/** Completion percentage 0-100 (derived) */
	completionPercentage?: number;
	/** Per-entity progress */
	entityStatuses?: {
		entityType?: string;
		notStarted?: number[];
		inProgress?: number[];
		completed?: number[];
	}[];
	/** Plan display name */
	name?: string;
	/** Plan owner user id */
	userId?: string;
	/** Plan metadata (tasks, sections, visibility, etc.) */
	metadata?: {
		tPublish?: number;
		planType?: string;
		planSubtype?: string;
		description?: string;
		planSections?: Record<string, unknown>[];
		planSectionsLayout?: Record<string, unknown>[];
		visibility?: string;
		permissions?: Record<string, unknown>[];
		planDurationDays?: number;
		tasks?: Record<string, unknown>;
		lastUpdateProfileId?: string;
	};
	/** Plan calibration data (skills, associated roles) */
	calibrationData?: {
		skills?: string[];
		associatedRoleId?: string[];
		businessUnits?: string[];
		jobFunctions?: string[];
		locations?: string[];
	};
}


export type UpskillPlanAssignmentList = ListEnvelope<UpskillPlanAssignment>;
export type UpskillPlanAssignmentBatch = BatchResponse<UpskillPlanAssignment>;
