// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: user_campaign (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface UserCampaign {
	/** User who initiated this user campaign */
	userId?: string;
	/** Id associated with the user campaign */
	id?: string;
	/** Name of the user campaign */
	name?: string;
	/** Timestamp when this user campaign was created */
	createdAt?: number;
	/** Timestamp when this user campaign was updated */
	updatedAt?: number;
	/** Subject of this user campaign */
	subject?: string;
	/** Name of the sender in email envelope of this user campaign */
	emailFromName?: string;
	/** Email from address of the email envelope for this user campaign */
	emailFromAddress?: string;
	/** Reply To as set in the email envelope of this user campaign */
	replyTo?: string;
	/** Status of this user campaign */
	status?: string;
}

export interface UserCampaignListFilters extends BaseListFilters {
	/** Limit on the total number of search results, defaults to 100 */
	queryLimit?: string;
	/** Filter on user id of the campaign */
	userId?: string;
	/** Filter on create timestamp of user campaign */
	createdAt?: string;
}

export type UserCampaignList = ListEnvelope<UserCampaign>;
export type UserCampaignBatch = BatchResponse<UserCampaign>;
