// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: user_calendar (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface UserCalendar {
	/** Id associated with the user calendar event */
	id?: number;
	/** User id of the user who created the calendar event */
	creatorUserId?: string;
	/** User id of the assignee for the calendar event */
	assigneeUserId?: string;
	/** Position id associated with the user calendar event */
	positionId?: number;
	/** Profile id of the candidate associated the user calendar event */
	profileId?: string;
	/** Template id associated with the user calendar event */
	templateId?: number;
	/** Planned Event associated with the user calendar event */
	plannedEvent?: {
		id?: string;
		name?: string;
		eventLandingPage?: string;
		activeRegistrations?: string;
		registerButton?: {
		text?: string;
		textColor?: string;
		backgroundColor?: string;
	};
		homePageBanner?: {
		image?: string;
		title?: string;
		useImage?: boolean;
	};
		selectedTimezone?: string;
		startTimestamp?: number;
		endTimestamp?: number;
		institution?: string;
		venue?: string;
		address?: string;
		description?: string;
		createdAt?: number;
		createdBy?: string;
		eventSpeakers?: string[];
		eventTeamDataJson?: Record<string, unknown>;
		eventCustomFieldsJson?: Record<string, unknown>;
		eventType?: string;
		isCancelled?: boolean;
		status?: string;
		eventLocationType?: string;
		isPublished?: boolean;
		eventBucket?: string;
		parentId?: string;
		eventCategory?: string;
		when?: string;
	};
	/** Planned Event id associated with the user calendar event */
	plannedEventId?: number;
	/** Timezone for the user calendar event */
	timezone?: string;
	/** Status of the user calendar event */
	status?: string;
	/** Timestamp when this user calendar event was created */
	createdAt?: number;
	/** Timestamp when this user calendar event was last updated */
	updatedAt?: number;
	/** Time duration in minutes of the user calendar event */
	durationMinutes?: number;
	/** Meeting timestamp for the user calendar event */
	meetingTime?: number;
	/** Candidate email for the user calendar event */
	candidateEmail?: string;
	/** Interview Slots */
	interviewSlotsJson?: Record<string, unknown>;
}

export interface UserCalendarListFilters extends BaseListFilters {
	/** Limit on the total number of search results, defaults to 100 */
	queryLimit?: string;
	/** Filter on User id who created the calendar event */
	creatorUserId?: string;
	/** Filter on position id associated with the calendar event */
	positionId?: string;
	/** Filter on profile id of the candidate */
	profileId?: string;
	/** Filter on candidate's email address */
	candidateEmail?: string;
	/** Filter on meeting time of the calendar event */
	meetingTime?: string;
	/** Filter on assignee user id of the calendar event */
	assigneeUserId?: string;
	/** Filter on the status of the calendar event */
	status?: string;
}

export type UserCalendarList = ListEnvelope<UserCalendar>;
export type UserCalendarBatch = BatchResponse<UserCalendar>;
