// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: user (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface User {
	/** Id of an User */
	id?: string;
	/** Email of User */
	email?: string;
	/** First Name of User */
	firstName?: string;
	/** Last Name of User */
	lastName?: string;
	/** Company of User */
	company?: string;
	/** Title of User */
	title?: string;
	/** Manager of User */
	manager?: string;
	/** Verified at timestamp of the User */
	verifiedAt?: number;
	/** Create timestamp of the User */
	createdAt?: number;
	/** Update timestamp of the User */
	updatedAt?: number;
	/** Roles of a user */
	roles?: string[];
	/** Access Mode of User */
	defaultAccessMode?: string;
	/** Timezone offset for a User */
	timezoneOffset?: number;
	/** Timezone name for a user */
	timezoneName?: string;
	/** If user is disabled or not */
	isDisabled?: boolean;
	/** ProfileId of User */
	profileId?: string;
	/** Email of User\ */
	managerEmail?: string;
	/** Last login time stamp of a user */
	lastLoginTimeStamp?: number;
	/** Ats Data of an User */
	atsData?: {
		atsUserGroups?: {
		userGroupId?: string;
	}[];
		userCountries?: {
		userCountryId?: string;
	}[];
	};
	/** External unique identifier such as UUID, Corporate ID and Employee ID */
	uuid?: string;
	/** HRBP Data of an User */
	hrbpData?: Record<string, unknown>;
	/** RM user groups associated with the user */
	rmUserGroups?: {
		userGroupId?: string;
	}[];
	/** Language preference of the user */
	language?: string;
}

export interface UserListFilters extends BaseListFilters {
	/** filter query using predefined filter arguments documented [here](https://apidocs.eightfold.ai/v2.0/docs#the-filterquery-parameter) */
	filterQuery?: string;
	/** any wildcard text to search in user data */
	query?: string;
}

export type UserList = ListEnvelope<User>;
export type UserBatch = BatchResponse<User>;
