// Generated by _generator/generate.ts. Do not hand-edit.
// Entity: user_message (core)

import type { ListEnvelope, BatchResponse, BaseListFilters } from "./shared";

export interface UserMessage {
	/** Position Id associated with the user message */
	positionId?: number;
	/** Profile Id associated with the user message */
	profileId?: string;
	/** Object id of the user message */
	id?: string;
	/** User who initiated sending this user message */
	userId?: string;
	/** Decrypted Event ID */
	plannedEventId?: number;
	/** Planned event associated with the user message */
	plannedEvent?: {
		id?: string;
		name?: string;
		eventLandingPage?: string;
		activeRegistrations?: string;
		registerButton?: {
		text?: string;
		textColor?: string;
		backgroundColor?: string;
	};
		homePageBanner?: {
		image?: string;
		title?: string;
		useImage?: boolean;
	};
		selectedTimezone?: string;
		startTimestamp?: number;
		endTimestamp?: number;
		institution?: string;
		venue?: string;
		address?: string;
		description?: string;
		createdAt?: number;
		createdBy?: string;
		eventSpeakers?: string[];
		eventTeamDataJson?: Record<string, unknown>;
		eventCustomFieldsJson?: Record<string, unknown>;
		eventType?: string;
		isCancelled?: boolean;
		status?: string;
		eventLocationType?: string;
		isPublished?: boolean;
		eventBucket?: string;
		parentId?: string;
		eventCategory?: string;
		when?: string;
	};
	/** Conversation Id associated with the user message */
	conversationId?: string;
	/** Conversation Type associated with the user message e.g. email, sms */
	conversationType?: string;
	/** Subject of the user message with type email */
	subject?: string;
	/** Recipient of the user message with type email */
	emailTo?: string;
	/** Sent-on-behalf-of if different from user_id of the user message with type email */
	emailFrom?: string;
	/** Reply-To as set in the email envelope of the user message with type email */
	emailReplyTo?: string;
	/** User Campaign Id associated with the user message */
	userCampaignId?: number;
	/** Template Id associated with the user message */
	templateId?: number;
	/** Email carbon copy addresses in comma separated format */
	emailCc?: string;
	/** Email blind carbon copy addresses in comma separated format */
	emailBcc?: string;
	/** Creation timestamp for the user message */
	createdAt?: number;
	/** Delivery timestamp for the user message */
	deliveryTime?: number;
	/** Read timestamp for the user message */
	readTime?: number;
	/** Reply timestamp for the user message */
	replyTime?: number;
	/** Click timestamp for the user message */
	clickTime?: number;
	/** Click count for the user message */
	clickCount?: number;
	/** Read count for the user message */
	readCount?: number;
	/** Email file content of the message. This is an email content with Internet Message Format specification (RFC 5322) */
	emailContent?: string;
	/** Workflow recipe id associated with user message */
	workflowRecipeId?: number;
	/** Status of the user message */
	status?: string;
	/** Reason of failure of the user message */
	failureReason?: string;
	/** Time of failure of the user message */
	failureTime?: number;
	/** Company name associated with user message */
	company?: string;
	/** JSON data for message content of the user message */
	messageContent?: {
		body?: string;
		attachments?: {
		fileName?: string;
		contentType?: string;
		content?: string;
		isBased64Encoded?: boolean;
	}[];
	};
	/** Recipient of the user message */
	messageTo?: string;
	/** Sender of the user message */
	messageFrom?: string;
	/** Parent message id of the user message */
	parentMessageId?: string;
}

export interface UserMessageListFilters extends BaseListFilters {
	/** Limit on the total number of search results, defaults to 100 */
	queryLimit?: string;
	/** Filter on user id of the message */
	userId?: string;
	/** Filter on profile id of the candidate */
	profileId?: string;
	/** Filter on position id associated with the message */
	positionId?: string;
	/** Filter on conversation id of the message */
	conversationId?: string;
	/** Filter on email address to which email message was addressed */
	emailTo?: string;
	/** Filter on email address from which email message was sent */
	emailFrom?: string;
	/** Filter on campaign id of the user message */
	userCampaignId?: string;
	/** Filter on template id of the user message */
	templateId?: string;
	/** Filter on create timestamp of user message */
	createdAt?: string;
	/** Filter on reply time of user message */
	replyTime?: string;
}

export type UserMessageList = ListEnvelope<UserMessage>;
export type UserMessageBatch = BatchResponse<UserMessage>;
