// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { AsyncApiStatus } from "../types/async-api-status";

export const _svcAsyncApiStatus = createEntityService<AsyncApiStatus, Record<string, unknown>, Partial<AsyncApiStatus>, Partial<AsyncApiStatus>>({
	entity: "async-api-status",
	namespace: "core",
	ops: {
		getById: { callerId: "transaction-get-by-id", method: "GET", path: "/transactions/{transactionId}" },
	},
});

export const getAsyncApiStatus = _svcAsyncApiStatus.getById;
