// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { AtsCandidate, AtsCandidateListFilters } from "../types/ats-candidate";

export const _svcAtsCandidate = createEntityService<AtsCandidate, AtsCandidateListFilters, Partial<AtsCandidate>, Partial<AtsCandidate>>({
	entity: "ats-candidate",
	namespace: "core",
	ops: {
		getById: { callerId: "ats-candidate-get-by-id", method: "GET", path: "/ats-systems/{systemId}/ats-candidates/{atsCandidateId}" },
		update: { callerId: "ats-candidate-update", method: "PUT", path: "/ats-systems/{systemId}/ats-candidates/{atsCandidateId}" },
		patch: { callerId: "ats-candidate-patch", method: "PATCH", path: "/ats-systems/{systemId}/ats-candidates/{atsCandidateId}" },
		list: { callerId: "ats-candidates-list-search", method: "GET", path: "/ats-systems/{systemId}/ats-candidates" },
		create: { callerId: "ats-candidate-create", method: "POST", path: "/ats-systems/{systemId}/ats-candidates" },
	},
});

export const getAtsCandidate = _svcAtsCandidate.getById;
export const listAtsCandidates = _svcAtsCandidate.list;
export const createAtsCandidate = _svcAtsCandidate.create;
export const updateAtsCandidate = _svcAtsCandidate.update;
export const patchAtsCandidate = _svcAtsCandidate.patch;
