// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService, type OpInvokeArgs } from "../service-factory";
import type { AtsPosition, AtsPositionListFilters } from "../types/ats-position";

export const _svcAtsPosition = createEntityService<AtsPosition, AtsPositionListFilters, Partial<AtsPosition>, Partial<AtsPosition>>({
	entity: "ats-position",
	namespace: "core",
	ops: {
		getById: { callerId: "ats-position-get-by-id", method: "GET", path: "/ats-systems/{systemId}/ats-positions/{atsPositionId}" },
		update: { callerId: "ats-position-update", method: "PUT", path: "/ats-systems/{systemId}/ats-positions/{atsPositionId}" },
		patch: { callerId: "ats-position-patch", method: "PATCH", path: "/ats-systems/{systemId}/ats-positions/{atsPositionId}" },
		list: { callerId: "ats-positions-list-search", method: "GET", path: "/ats-systems/{systemId}/ats-positions" },
		create: { callerId: "ats-position-create", method: "POST", path: "/ats-systems/{systemId}/ats-positions" },
		createAttachments: { callerId: "ats-position-upload-attachments", method: "POST", path: "/ats-systems/{systemId}/ats-positions/{atsPositionId}/attachments" },
	},
});

export const getAtsPosition = _svcAtsPosition.getById;
export const listAtsPositions = _svcAtsPosition.list;
export const createAtsPosition = _svcAtsPosition.create;
export const updateAtsPosition = _svcAtsPosition.update;
export const patchAtsPosition = _svcAtsPosition.patch;
/** Upload ATS Position Attachments — POST /ats-systems/{systemId}/ats-positions/{atsPositionId}/attachments */
export const createAttachmentsAtsPosition = (args?: OpInvokeArgs) => _svcAtsPosition.call("createAttachments", args);
