// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { Booking, BookingListFilters } from "../types/booking";

export const _svcBooking = createEntityService<Booking, BookingListFilters, Partial<Booking>, Partial<Booking>>({
	entity: "booking",
	namespace: "resource_management",
	ops: {
		list: { callerId: "bookings-list-search", method: "GET", path: "/bookings" },
	},
});

export const listBookings = _svcBooking.list;
