// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { CareerNavigator, CareerNavigatorListFilters } from "../types/career-navigator";

export const _svcCareerNavigator = createEntityService<CareerNavigator, CareerNavigatorListFilters, Partial<CareerNavigator>, Partial<CareerNavigator>>({
	entity: "career-navigator",
	namespace: "careerhub",
	ops: {
		getById: { callerId: "career-navigator-search", method: "GET", path: "/career-navigator/recommended-paths/{userEmail}" },
		list: { callerId: "career-navigator-recommended-courses-list", method: "GET", path: "/career-navigator/recommended-courses/{userEmail}" },
	},
});

export const getCareerNavigator = _svcCareerNavigator.getById;
export const listCareerNavigators = _svcCareerNavigator.list;
