// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService, type OpInvokeArgs } from "../service-factory";
import type { Careerhub } from "../types/careerhub";

export const _svcCareerhub = createEntityService<Careerhub, Record<string, unknown>, Partial<Careerhub>, Partial<Careerhub>>({
	entity: "careerhub",
	namespace: "careerhub",
	ops: {
		getById: { callerId: "careerhub-suggest-skills-get-by-id", method: "GET", path: "/profiles/suggest-skills/{profileSection}" },
		getByIdCareerPlannerRoles: { callerId: "careerhub-career-planner-roles-get-by-id", method: "GET", path: "/career-planner/{userEmail}/roles/{roleSection}" },
		patch: { callerId: "careerhub-career-planner-role-patch", method: "PATCH", path: "/career-planner/{userEmail}/roles/" },
		getByIdCareerPlannerSkills: { callerId: "careerhub-career-planner-skills-get-by-id", method: "GET", path: "/career-planner/{userEmail}/skills/skill-gap-analysis" },
		getByIdCareerPlannerCourses: { callerId: "careerhub-career-planner-courses-get-by-id", method: "GET", path: "/career-planner/{userEmail}/courses/recommended-courses" },
	},
});

export const getCareerhub = _svcCareerhub.getById;
export const patchCareerhub = _svcCareerhub.patch;
/** Get Career Planner Role — GET /career-planner/{userEmail}/roles/{roleSection} */
export const getByIdCareerPlannerRolesCareerhub = (args?: OpInvokeArgs) => _svcCareerhub.call("getByIdCareerPlannerRoles", args);
/** Get Skill Gap Analysis — GET /career-planner/{userEmail}/skills/skill-gap-analysis */
export const getByIdCareerPlannerSkillsCareerhub = (args?: OpInvokeArgs) => _svcCareerhub.call("getByIdCareerPlannerSkills", args);
/** Get Recommended Courses — GET /career-planner/{userEmail}/courses/recommended-courses */
export const getByIdCareerPlannerCoursesCareerhub = (args?: OpInvokeArgs) => _svcCareerhub.call("getByIdCareerPlannerCourses", args);
