// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService, type OpInvokeArgs } from "../service-factory";
import type { Connectors } from "../types/connectors";

export const _svcConnectors = createEntityService<Connectors, Record<string, unknown>, Partial<Connectors>, Partial<Connectors>>({
	entity: "connectors",
	namespace: "connectors",
	ops: {
		list: { callerId: "list-integrations", method: "GET", path: "/integrations" },
		listToken: { callerId: "get-connectors-oauth-access-token", method: "GET", path: "/oauth-access-token" },
		create: { callerId: "connections-sync-status", method: "POST", path: "/sync_status" },
	},
});

export const listConnectorses = _svcConnectors.list;
export const createConnectors = _svcConnectors.create;
/** Get OAuth Access Token — GET /oauth-access-token */
export const listTokenConnectors = (args?: OpInvokeArgs) => _svcConnectors.call("listToken", args);
