// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { Course, CourseListFilters } from "../types/course";

export const _svcCourse = createEntityService<Course, CourseListFilters, Partial<Course>, Partial<Course>>({
	entity: "course",
	namespace: "core",
	ops: {
		getById: { callerId: "course-get-by-id", method: "GET", path: "/courses/{courseId}" },
		delete: { callerId: "course-delete", method: "DELETE", path: "/courses/{courseId}" },
		patch: { callerId: "course-patch", method: "PATCH", path: "/courses/{courseId}" },
		list: { callerId: "courses-list-search", method: "GET", path: "/courses" },
		create: { callerId: "course-create", method: "POST", path: "/courses" },
	},
});

export const getCourse = _svcCourse.getById;
export const listCourses = _svcCourse.list;
export const createCourse = _svcCourse.create;
export const patchCourse = _svcCourse.patch;
export const deleteCourse = _svcCourse.delete;
