// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService, type OpInvokeArgs } from "../service-factory";
import type { Demand, DemandListFilters } from "../types/demand";

export const _svcDemand = createEntityService<Demand, DemandListFilters, Partial<Demand>, Partial<Demand>>({
	entity: "demand",
	namespace: "core",
	ops: {
		listSearch: { callerId: "employee-matched-demands-list-search", method: "GET", path: "/employees/{profileId}/matched-demands" },
		list: { callerId: "demands-list-search", method: "GET", path: "/demands" },
	},
});

export const listDemands = _svcDemand.list;
/** List Matched Demands for Employee — GET /employees/{profileId}/matched-demands */
export const listSearchDemand = (args?: OpInvokeArgs) => _svcDemand.call("listSearch", args);
