// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { EmailDeliveryFeedback, EmailDeliveryFeedbackListFilters } from "../types/email-delivery-feedback";

export const _svcEmailDeliveryFeedback = createEntityService<EmailDeliveryFeedback, EmailDeliveryFeedbackListFilters, Partial<EmailDeliveryFeedback>, Partial<EmailDeliveryFeedback>>({
	entity: "email-delivery-feedback",
	namespace: "core",
	ops: {
		getById: { callerId: "email-delivery-feedback-get-by-id", method: "GET", path: "/email-delivery-feedbacks/{emailDeliveryFeedbackId}" },
		batchFetch: { callerId: "email-delivery-feedback-batch-fetch", method: "POST", path: "/email-delivery-feedbacks/batch-fetch" },
		list: { callerId: "email-delivery-feedbacks-list-search", method: "GET", path: "/email-delivery-feedbacks" },
	},
});

export const getEmailDeliveryFeedback = _svcEmailDeliveryFeedback.getById;
export const listEmailDeliveryFeedbacks = _svcEmailDeliveryFeedback.list;
export const batchFetchEmailDeliveryFeedbacks = _svcEmailDeliveryFeedback.batchFetch;
