// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService, type OpInvokeArgs } from "../service-factory";
import type { Employee, EmployeeListFilters } from "../types/employee";

export const _svcEmployee = createEntityService<Employee, EmployeeListFilters, Partial<Employee>, Partial<Employee>>({
	entity: "employee",
	namespace: "core",
	ops: {
		getByIdRole: { callerId: "role-get-by-id", method: "GET", path: "/employee-roles/{roleId}" },
		createRole: { callerId: "role-create", method: "POST", path: "/employee-roles" },
		getById: { callerId: "employee-get-by-profile-id", method: "GET", path: "/employees/{profileId}" },
		patch: { callerId: "employee-patch", method: "PATCH", path: "/employees/{profileId}" },
		update: { callerId: "employee-update", method: "PUT", path: "/employees/{profileId}" },
		create: { callerId: "employee-create", method: "POST", path: "/employees" },
		list: { callerId: "employees-list", method: "GET", path: "/employees" },
		batchFetch: { callerId: "employee-batch-fetch", method: "POST", path: "/employees/batch-fetch" },
		listEmployeesRecommendedMentors: { callerId: "employees-recommended-mentors-list", method: "GET", path: "/employees/{profileId}/recommended-mentors" },
		listEmployeesRoleMatchScore: { callerId: "employees-role-match-score-list", method: "GET", path: "/employees/role-match-score" },
	},
});

export const getEmployee = _svcEmployee.getById;
export const listEmployees = _svcEmployee.list;
export const batchFetchEmployees = _svcEmployee.batchFetch;
export const createEmployee = _svcEmployee.create;
export const updateEmployee = _svcEmployee.update;
export const patchEmployee = _svcEmployee.patch;
/** Get Employee Role — GET /employee-roles/{roleId} */
export const getByIdRoleEmployee = (args?: OpInvokeArgs) => _svcEmployee.call("getByIdRole", args);
/** Create Employee Role — POST /employee-roles */
export const createRoleEmployee = (args?: OpInvokeArgs) => _svcEmployee.call("createRole", args);
/** List Recommended Mentors — GET /employees/{profileId}/recommended-mentors */
export const listEmployeesRecommendedMentors = (args?: OpInvokeArgs) => _svcEmployee.call("listEmployeesRecommendedMentors", args);
/** List Employee Match Scores — GET /employees/role-match-score */
export const listEmployeesRoleMatchScore = (args?: OpInvokeArgs) => _svcEmployee.call("listEmployeesRoleMatchScore", args);
