// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { EntityChangelog, EntityChangelogListFilters } from "../types/entity-changelog";

export const _svcEntityChangelog = createEntityService<EntityChangelog, EntityChangelogListFilters, Partial<EntityChangelog>, Partial<EntityChangelog>>({
	entity: "entity-changelog",
	namespace: "core",
	ops: {
		list: { callerId: "changelog-modified-entity-ids", method: "GET", path: "/changelog/{entityType}" },
	},
});

export const listEntityChangelogs = _svcEntityChangelog.list;
