// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { Event } from "../types/event";

export const _svcEvent = createEntityService<Event, Record<string, unknown>, Partial<Event>, Partial<Event>>({
	entity: "event",
	namespace: "events",
	ops: {
		list: { callerId: "planned-events-list-search", method: "GET", path: "/planned-events" },
		batchFetch: { callerId: "planned-event-batch-fetch", method: "POST", path: "/planned-events/batch-fetch" },
		getById: { callerId: "planned-event-get-by-id", method: "GET", path: "/planned-events/{plannedEventId}" },
	},
});

export const getEvent = _svcEvent.getById;
export const listEvents = _svcEvent.list;
export const batchFetchEvents = _svcEvent.batchFetch;
