// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { EventCandidateActivity } from "../types/event-candidate-activity";

export const _svcEventCandidateActivity = createEntityService<EventCandidateActivity, Record<string, unknown>, Partial<EventCandidateActivity>, Partial<EventCandidateActivity>>({
	entity: "event-candidate-activity",
	namespace: "events",
	ops: {
		getById: { callerId: "event-candidate-activity-get-by-id", method: "GET", path: "/event-candidate-activities/{eventActivityId}" },
		batchFetch: { callerId: "event-candidate-activity-batch-fetch", method: "POST", path: "/event-candidate-activities/batch-fetch" },
	},
});

export const getEventCandidateActivity = _svcEventCandidateActivity.getById;
export const batchFetchEventCandidateActivities = _svcEventCandidateActivity.batchFetch;
