// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { ExtDemand, ExtDemandListFilters } from "../types/ext-demand";

export const _svcExtDemand = createEntityService<ExtDemand, ExtDemandListFilters, Partial<ExtDemand>, Partial<ExtDemand>>({
	entity: "ext-demand",
	namespace: "resource_management",
	ops: {
		list: { callerId: "ext-demands-list-search", method: "GET", path: "/ext-systems/resourcing/ext-demands" },
	},
});

export const listExtDemands = _svcExtDemand.list;
