// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService, type OpInvokeArgs } from "../service-factory";
import type { ExtAiInterview } from "../types/ext-ai-interview";

export const _svcExtAiInterview = createEntityService<ExtAiInterview, Record<string, unknown>, Partial<ExtAiInterview>, Partial<ExtAiInterview>>({
	entity: "ext-ai-interview",
	namespace: "agent_kit",
	ops: {
		list: { callerId: "ext-ai-interview-guides-list", method: "GET", path: "/ext-systems/{systemId}/ext-ai-interview/guides" },
		create: { callerId: "ext-ai-interview-schedule-interview", method: "POST", path: "/ext-systems/{systemId}/ext-ai-interview/schedule-interview" },
		listLink: { callerId: "ext-ai-interview-feedback-link", method: "GET", path: "/ext-systems/{systemId}/ext-ai-interview/interview-feedback-link" },
	},
});

export const listExtAiInterviews = _svcExtAiInterview.list;
export const createExtAiInterview = _svcExtAiInterview.create;
/** Get Interview Feedback Link — GET /ext-systems/{systemId}/ext-ai-interview/interview-feedback-link */
export const listLinkExtAiInterview = (args?: OpInvokeArgs) => _svcExtAiInterview.call("listLink", args);
