// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { HiringCompanyHiringCompany } from "../types/hiring-company-hiring-company";

export const _svcHiringCompanyHiringCompany = createEntityService<HiringCompanyHiringCompany, Record<string, unknown>, Partial<HiringCompanyHiringCompany>, Partial<HiringCompanyHiringCompany>>({
	entity: "hiring-company-hiring-company",
	namespace: "etx",
	ops: {
		getById: { callerId: "hiring-company-get-by-id", method: "GET", path: "/hiring_company/{hiringCompanyGroupId}" },
		patch: { callerId: "hiring-company-patch", method: "PATCH", path: "/hiring_company/{hiringCompanyGroupId}" },
	},
});

export const getHiringCompanyHiringCompany = _svcHiringCompanyHiringCompany.getById;
export const patchHiringCompanyHiringCompany = _svcHiringCompanyHiringCompany.patch;
