// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { Holiday, HolidayListFilters } from "../types/holiday";

export const _svcHoliday = createEntityService<Holiday, HolidayListFilters, Partial<Holiday>, Partial<Holiday>>({
	entity: "holiday",
	namespace: "resource_management",
	ops: {
		list: { callerId: "holidays-list-search", method: "GET", path: "/holidays" },
	},
});

export const listHolidays = _svcHoliday.list;
