// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { HrisEmployee, HrisEmployeeListFilters } from "../types/hris-employee";

export const _svcHrisEmployee = createEntityService<HrisEmployee, HrisEmployeeListFilters, Partial<HrisEmployee>, Partial<HrisEmployee>>({
	entity: "hris-employee",
	namespace: "core",
	ops: {
		patch: { callerId: "employee-patch-hris", method: "PATCH", path: "/hris-systems/{systemId}/ext-employees/{employeeId}" },
		update: { callerId: "employee-update-hris", method: "PUT", path: "/hris-systems/{systemId}/ext-employees/{employeeId}" },
		getById: { callerId: "hris-employee-get-by-id", method: "GET", path: "/hris-systems/{systemId}/hris-employees/{uniqueIdentifier}" },
		list: { callerId: "hris-employees-list", method: "GET", path: "/hris-systems/{systemId}/hris-employees" },
	},
});

export const getHrisEmployee = _svcHrisEmployee.getById;
export const listHrisEmployees = _svcHrisEmployee.list;
export const updateHrisEmployee = _svcHrisEmployee.update;
export const patchHrisEmployee = _svcHrisEmployee.patch;
