// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService, type OpInvokeArgs } from "../service-factory";
import type { Insight, InsightListFilters } from "../types/insight";

export const _svcInsight = createEntityService<Insight, InsightListFilters, Partial<Insight>, Partial<Insight>>({
	entity: "insight",
	namespace: "insights",
	ops: {
		list: { callerId: "profile-insights-list-search", method: "GET", path: "/profile-insights" },
		create: { callerId: "talent-traits-insights-create", method: "POST", path: "/talent-traits" },
		listEmployeesDiversityInsights: { callerId: "employees-diversity-insights-list", method: "GET", path: "/diversity/employees" },
	},
});

export const listInsights = _svcInsight.list;
export const createInsight = _svcInsight.create;
/** Get Employee Diversity Insights — GET /diversity/employees */
export const listEmployeesDiversityInsights = (args?: OpInvokeArgs) => _svcInsight.call("listEmployeesDiversityInsights", args);
