// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService, type OpInvokeArgs } from "../service-factory";
import type { Jie, JieListFilters } from "../types/jie";

export const _svcJie = createEntityService<Jie, JieListFilters, Partial<Jie>, Partial<Jie>>({
	entity: "jie",
	namespace: "JIE",
	ops: {
		getById: { callerId: "JIE_role-get-by-id", method: "GET", path: "/roles/{roleId}" },
		update: { callerId: "JIE_role-update", method: "PUT", path: "/roles/{roleId}" },
		delete: { callerId: "JIE_role-delete", method: "DELETE", path: "/roles/{roleId}" },
		listJIEInsights: { callerId: "JIE-insights-list", method: "GET", path: "/insights" },
		create: { callerId: "JIE_role-create", method: "POST", path: "/roles" },
		list: { callerId: "JIE_role-list", method: "GET", path: "/roles" },
	},
});

export const getJie = _svcJie.getById;
export const listJies = _svcJie.list;
export const createJie = _svcJie.create;
export const updateJie = _svcJie.update;
export const deleteJie = _svcJie.delete;
/** Get Succession Plan — GET /insights */
export const listJIEInsights = (args?: OpInvokeArgs) => _svcJie.call("listJIEInsights", args);
