// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { Offer, OfferListFilters } from "../types/offer";

export const _svcOffer = createEntityService<Offer, OfferListFilters, Partial<Offer>, Partial<Offer>>({
	entity: "offer",
	namespace: "ats",
	ops: {
		list: { callerId: "offers-list-search", method: "GET", path: "/offers" },
	},
});

export const listOffers = _svcOffer.list;
