// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService, type OpInvokeArgs } from "../service-factory";
import type { OrgUnit, OrgUnitListFilters } from "../types/org-unit";

export const _svcOrgUnit = createEntityService<OrgUnit, OrgUnitListFilters, Partial<OrgUnit>, Partial<OrgUnit>>({
	entity: "org-unit",
	namespace: "t3s",
	ops: {
		list: { callerId: "org-units-list-search", method: "GET", path: "/org-units" },
		listSearch: { callerId: "foundational-data-list-search", method: "GET", path: "/foundational-data" },
	},
});

export const listOrgUnits = _svcOrgUnit.list;
/** List Foundational Data — GET /foundational-data */
export const listSearchOrgUnit = (args?: OpInvokeArgs) => _svcOrgUnit.call("listSearch", args);
