// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService, type OpInvokeArgs } from "../service-factory";
import type { PerformanceFeedback, PerformanceFeedbackListFilters } from "../types/performance-feedback";

export const _svcPerformanceFeedback = createEntityService<PerformanceFeedback, PerformanceFeedbackListFilters, Partial<PerformanceFeedback>, Partial<PerformanceFeedback>>({
	entity: "performance-feedback",
	namespace: "careerhub",
	ops: {
		list: { callerId: "performance-feedback-list", method: "GET", path: "/performance-feedback" },
		createRequest: { callerId: "performance-feedback-request", method: "POST", path: "/performance-feedback/request" },
		create: { callerId: "performance-feedback-provide", method: "POST", path: "/performance-feedback/provide" },
		getById: { callerId: "performance-feedback-get-by-id", method: "GET", path: "/performance-feedback/{reviewId}" },
	},
});

export const getPerformanceFeedback = _svcPerformanceFeedback.getById;
export const listPerformanceFeedbacks = _svcPerformanceFeedback.list;
export const createPerformanceFeedback = _svcPerformanceFeedback.create;
/** Request Performance Feedback — POST /performance-feedback/request */
export const createRequestPerformanceFeedback = (args?: OpInvokeArgs) => _svcPerformanceFeedback.call("createRequest", args);
