// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService, type OpInvokeArgs } from "../service-factory";
import type { Position, PositionListFilters } from "../types/position";

export const _svcPosition = createEntityService<Position, PositionListFilters, Partial<Position>, Partial<Position>>({
	entity: "position",
	namespace: "core",
	ops: {
		listSearch: { callerId: "profile-matched-positions-list-search", method: "GET", path: "/profiles/{profileId}/matched-positions" },
		getById: { callerId: "position-get-by-id", method: "GET", path: "/positions/{positionId}" },
		update: { callerId: "position-update", method: "PUT", path: "/positions/{positionId}" },
		patch: { callerId: "position-patch", method: "PATCH", path: "/positions/{positionId}" },
		list: { callerId: "positions-list-search", method: "GET", path: "/positions" },
		create: { callerId: "position-create", method: "POST", path: "/positions" },
		batchFetch: { callerId: "position-batch-fetch", method: "POST", path: "/positions/batch-fetch" },
	},
});

export const getPosition = _svcPosition.getById;
export const listPositions = _svcPosition.list;
export const batchFetchPositions = _svcPosition.batchFetch;
export const createPosition = _svcPosition.create;
export const updatePosition = _svcPosition.update;
export const patchPosition = _svcPosition.patch;
/** List Matched Positions for Profile — GET /profiles/{profileId}/matched-positions */
export const listSearchPosition = (args?: OpInvokeArgs) => _svcPosition.call("listSearch", args);
