// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { ProfileFeedback, ProfileFeedbackListFilters } from "../types/profile-feedback";

export const _svcProfileFeedback = createEntityService<ProfileFeedback, ProfileFeedbackListFilters, Partial<ProfileFeedback>, Partial<ProfileFeedback>>({
	entity: "profile-feedback",
	namespace: "core",
	ops: {
		getById: { callerId: "profile-feedback-get-by-id", method: "GET", path: "/profile-feedbacks/{profileFeedbackId}" },
		batchFetch: { callerId: "profile-feedback-batch-fetch", method: "POST", path: "/profile-feedbacks/batch-fetch" },
		list: { callerId: "profile-feedbacks-list-search", method: "GET", path: "/profile-feedbacks" },
	},
});

export const getProfileFeedback = _svcProfileFeedback.getById;
export const listProfileFeedbacks = _svcProfileFeedback.list;
export const batchFetchProfileFeedbacks = _svcProfileFeedback.batchFetch;
