// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { ProfileTag, ProfileTagListFilters } from "../types/profile-tag";

export const _svcProfileTag = createEntityService<ProfileTag, ProfileTagListFilters, Partial<ProfileTag>, Partial<ProfileTag>>({
	entity: "profile-tag",
	namespace: "core",
	ops: {
		getById: { callerId: "profile-tag-get-by-id", method: "GET", path: "/profile-tags/{profileTagId}" },
		batchFetch: { callerId: "profile-tag-batch-fetch", method: "POST", path: "/profile-tags/batch-fetch" },
		list: { callerId: "profile-tags-list-search", method: "GET", path: "/profile-tags" },
	},
});

export const getProfileTag = _svcProfileTag.getById;
export const listProfileTags = _svcProfileTag.list;
export const batchFetchProfileTags = _svcProfileTag.batchFetch;
