// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { ProfileNote, ProfileNoteListFilters } from "../types/profile-note";

export const _svcProfileNote = createEntityService<ProfileNote, ProfileNoteListFilters, Partial<ProfileNote>, Partial<ProfileNote>>({
	entity: "profile-note",
	namespace: "core",
	ops: {
		getById: { callerId: "profile-note-get-by-id", method: "GET", path: "/profile-notes/{profileNoteId}" },
		batchFetch: { callerId: "profile-note-batch-fetch", method: "POST", path: "/profile-notes/batch-fetch" },
		list: { callerId: "profile-notes-list-search", method: "GET", path: "/profile-notes" },
		create: { callerId: "profile-note-create", method: "POST", path: "/profile-notes" },
	},
});

export const getProfileNote = _svcProfileNote.getById;
export const listProfileNotes = _svcProfileNote.list;
export const batchFetchProfileNotes = _svcProfileNote.batchFetch;
export const createProfileNote = _svcProfileNote.create;
