// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { ProfileEventCalendar, ProfileEventCalendarListFilters } from "../types/profile-event-calendar";

export const _svcProfileEventCalendar = createEntityService<ProfileEventCalendar, ProfileEventCalendarListFilters, Partial<ProfileEventCalendar>, Partial<ProfileEventCalendar>>({
	entity: "profile-event-calendar",
	namespace: "events",
	ops: {
		list: { callerId: "event-candidate-activities-list-search", method: "GET", path: "/event-candidate-activities" },
	},
});

export const listProfileEventCalendars = _svcProfileEventCalendar.list;
