// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { ProfileApplication, ProfileApplicationListFilters } from "../types/profile-application";

export const _svcProfileApplication = createEntityService<ProfileApplication, ProfileApplicationListFilters, Partial<ProfileApplication>, Partial<ProfileApplication>>({
	entity: "profile-application",
	namespace: "core",
	ops: {
		getById: { callerId: "profile-application-get-by-id", method: "GET", path: "/profile-applications/{profileApplicationId}" },
		batchFetch: { callerId: "profile-application-batch-fetch", method: "POST", path: "/profile-applications/batch-fetch" },
		list: { callerId: "profile-applications-list-search", method: "GET", path: "/profile-applications" },
	},
});

export const getProfileApplication = _svcProfileApplication.getById;
export const listProfileApplications = _svcProfileApplication.list;
export const batchFetchProfileApplications = _svcProfileApplication.batchFetch;
