// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService, type OpInvokeArgs } from "../service-factory";
import type { Profile, ProfileListFilters } from "../types/profile";

export const _svcProfile = createEntityService<Profile, ProfileListFilters, Partial<Profile>, Partial<Profile>>({
	entity: "profile",
	namespace: "core",
	ops: {
		getByIdAttachment: { callerId: "profile-attachment-get-by-id", method: "GET", path: "/profiles/{profileId}/attachments/{attachmentId}" },
		listSearch: { callerId: "position-matched-candidates-list-search", method: "GET", path: "/positions/{positionId}/matched-candidates" },
		listSearch2: { callerId: "position-list-applicants-search", method: "GET", path: "/position/{positionId}/applicants" },
		getById: { callerId: "profile-get-by-id", method: "GET", path: "/profiles/{profileId}" },
		update: { callerId: "profile-update", method: "PUT", path: "/profiles/{profileId}" },
		delete: { callerId: "profile-delete", method: "DELETE", path: "/profiles/{profileId}" },
		patch: { callerId: "profile-patch", method: "PATCH", path: "/profiles/{profileId}" },
		list: { callerId: "profiles-list-search", method: "GET", path: "/profiles" },
		create: { callerId: "profile-create", method: "POST", path: "/profiles" },
		createStage: { callerId: "create-or-advance-application-stage", method: "POST", path: "/profiles/{profileId}/application/stages" },
		batchFetch: { callerId: "profile-batch-fetch", method: "POST", path: "/profiles/batch-fetch" },
	},
});

export const getProfile = _svcProfile.getById;
export const listProfiles = _svcProfile.list;
export const batchFetchProfiles = _svcProfile.batchFetch;
export const createProfile = _svcProfile.create;
export const updateProfile = _svcProfile.update;
export const patchProfile = _svcProfile.patch;
export const deleteProfile = _svcProfile.delete;
/** Get Attachment — GET /profiles/{profileId}/attachments/{attachmentId} */
export const getByIdAttachmentProfile = (args?: OpInvokeArgs) => _svcProfile.call("getByIdAttachment", args);
/** List Matched Candidates for Position — GET /positions/{positionId}/matched-candidates */
export const listSearchProfile = (args?: OpInvokeArgs) => _svcProfile.call("listSearch", args);
/** List Applicants — GET /position/{positionId}/applicants */
export const listSearch2Profile = (args?: OpInvokeArgs) => _svcProfile.call("listSearch2", args);
/** Upsert Application Stage — POST /profiles/{profileId}/application/stages */
export const createStageProfile = (args?: OpInvokeArgs) => _svcProfile.call("createStage", args);
