// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { ProfileEntityApplication, ProfileEntityApplicationListFilters } from "../types/profile-entity-application";

export const _svcProfileEntityApplication = createEntityService<ProfileEntityApplication, ProfileEntityApplicationListFilters, Partial<ProfileEntityApplication>, Partial<ProfileEntityApplication>>({
	entity: "profile-entity-application",
	namespace: "core",
	ops: {
		getById: { callerId: "entity-profile-application-get-by-id", method: "GET", path: "/entity-profile-applications/{entityType}/{applicationId}" },
		batchFetch: { callerId: "entity-profile-application-batch-fetch", method: "POST", path: "/entity-profile-applications/{entityType}/batch-fetch" },
		list: { callerId: "entity-profile-applications-list-search", method: "GET", path: "/entity-profile-applications/{entityType}" },
	},
});

export const getProfileEntityApplication = _svcProfileEntityApplication.getById;
export const listProfileEntityApplications = _svcProfileEntityApplication.list;
export const batchFetchProfileEntityApplications = _svcProfileEntityApplication.batchFetch;
