// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService, type OpInvokeArgs } from "../service-factory";
import type { ResourceManagement, ResourceManagementListFilters } from "../types/resource-management";

export const _svcResourceManagement = createEntityService<ResourceManagement, ResourceManagementListFilters, Partial<ResourceManagement>, Partial<ResourceManagement>>({
	entity: "resource-management",
	namespace: "core",
	ops: {
		getById: { callerId: "comment-get-by-id", method: "GET", path: "/comments/{commentId}" },
		list: { callerId: "comments-list", method: "GET", path: "/comments" },
		listType: { callerId: "comments-get-by-ext-entity-id-and-type", method: "GET", path: "/ext-entity-comments/{entityType}/{extEntityId}" },
		listType2: { callerId: "comments-get-by-entity-id-and-type", method: "GET", path: "/entity-comments/{entityType}/{entityId}" },
		delete: { callerId: "delete-entity-comments-by-entity-id", method: "DELETE", path: "/entity-comments/{entityType}/{entityId}" },
		batchGetByIdsIds: { callerId: "batch-get-by-entity-ids", method: "POST", path: "/entity-comments-batch-fetch" },
		batchGetByIdsIds2: { callerId: "batch-get-by-external-entity-ids", method: "POST", path: "/ext-entity-comments-batch-fetch" },
	},
});

export const getResourceManagement = _svcResourceManagement.getById;
export const listResourceManagements = _svcResourceManagement.list;
export const deleteResourceManagement = _svcResourceManagement.delete;
/** Get Comments By External Entity Id And Type — GET /ext-entity-comments/{entityType}/{extEntityId} */
export const listTypeResourceManagement = (args?: OpInvokeArgs) => _svcResourceManagement.call("listType", args);
/** Get Comments By Entity Id And Type — GET /entity-comments/{entityType}/{entityId} */
export const listType2ResourceManagement = (args?: OpInvokeArgs) => _svcResourceManagement.call("listType2", args);
/** Batch Fetch Comments By Entity IDs — POST /entity-comments-batch-fetch */
export const batchGetByIdsIdsResourceManagement = (args?: OpInvokeArgs) => _svcResourceManagement.call("batchGetByIdsIds", args);
/** Batch Fetch Comments By External Entity IDs — POST /ext-entity-comments-batch-fetch */
export const batchGetByIdsIds2ResourceManagement = (args?: OpInvokeArgs) => _svcResourceManagement.call("batchGetByIdsIds2", args);
