// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService, type OpInvokeArgs } from "../service-factory";
import type { SuccessionPlan, SuccessionPlanListFilters } from "../types/succession-plan";

export const _svcSuccessionPlan = createEntityService<SuccessionPlan, SuccessionPlanListFilters, Partial<SuccessionPlan>, Partial<SuccessionPlan>>({
	entity: "succession-plan",
	namespace: "careerhub",
	ops: {
		getById: { callerId: "succession-plan-get-by-position-id", method: "GET", path: "/succession_plans/{positionId}" },
		delete: { callerId: "succession-plan-delete", method: "DELETE", path: "/succession_plans/{positionId}" },
		patch: { callerId: "succession-plan-patch", method: "PATCH", path: "/succession_plans/{positionId}" },
		listSuccessors: { callerId: "succession-plan-recommended-successors", method: "GET", path: "/succession_plans/{positionId}/recommended_successors" },
		list: { callerId: "succession-plan-list", method: "GET", path: "/succession_plans" },
		create: { callerId: "succession-plan-create", method: "POST", path: "/succession_plans" },
		listIncumbent: { callerId: "succession-plan-incumbent-list", method: "GET", path: "/succession_plans/{positionId}/incumbents" },
		createSuccessor: { callerId: "succession-plan-successor-create", method: "POST", path: "/succession_plans/{positionId}/successors" },
		patchSuccessor: { callerId: "succession-plan-successor-patch", method: "PATCH", path: "/succession_plans/{positionId}/successors/{profileId}" },
		deleteSuccessor: { callerId: "succession-plan-successor-delete", method: "DELETE", path: "/succession_plans/{positionId}/successors/{profileId}" },
		createCaretaker: { callerId: "succession-plan-caretaker-create", method: "POST", path: "/succession_plans/{positionId}/caretakers" },
		deleteCaretaker: { callerId: "succession-plan-caretaker-delete", method: "DELETE", path: "/succession_plans/{positionId}/caretakers/{profileId}" },
	},
});

export const getSuccessionPlan = _svcSuccessionPlan.getById;
export const listSuccessionPlans = _svcSuccessionPlan.list;
export const createSuccessionPlan = _svcSuccessionPlan.create;
export const patchSuccessionPlan = _svcSuccessionPlan.patch;
export const deleteSuccessionPlan = _svcSuccessionPlan.delete;
/** Get Recommended Successors — GET /succession_plans/{positionId}/recommended_successors */
export const listSuccessorsSuccessionPlan = (args?: OpInvokeArgs) => _svcSuccessionPlan.call("listSuccessors", args);
/** List Succession Plan Incumbents — GET /succession_plans/{positionId}/incumbents */
export const listIncumbentSuccessionPlan = (args?: OpInvokeArgs) => _svcSuccessionPlan.call("listIncumbent", args);
/** Create Succession Plan Successor — POST /succession_plans/{positionId}/successors */
export const createSuccessorSuccessionPlan = (args?: OpInvokeArgs) => _svcSuccessionPlan.call("createSuccessor", args);
/** Patch Succession Plan Successor — PATCH /succession_plans/{positionId}/successors/{profileId} */
export const patchSuccessorSuccessionPlan = (args?: OpInvokeArgs) => _svcSuccessionPlan.call("patchSuccessor", args);
/** Delete Succession Plan Successor — DELETE /succession_plans/{positionId}/successors/{profileId} */
export const deleteSuccessorSuccessionPlan = (args?: OpInvokeArgs) => _svcSuccessionPlan.call("deleteSuccessor", args);
/** Create Succession Plan Caretaker — POST /succession_plans/{positionId}/caretakers */
export const createCaretakerSuccessionPlan = (args?: OpInvokeArgs) => _svcSuccessionPlan.call("createCaretaker", args);
/** Delete Succession Plan Caretaker — DELETE /succession_plans/{positionId}/caretakers/{profileId} */
export const deleteCaretakerSuccessionPlan = (args?: OpInvokeArgs) => _svcSuccessionPlan.call("deleteCaretaker", args);
