// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { TalentPool } from "../types/talent-pool";

export const _svcTalentPool = createEntityService<TalentPool, Record<string, unknown>, Partial<TalentPool>, Partial<TalentPool>>({
	entity: "talent-pool",
	namespace: "smartapply",
	ops: {
		create: { callerId: "talent-pool-create", method: "POST", path: "/talent-pool" },
	},
});

export const createTalentPool = _svcTalentPool.create;
