// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { UpskillPlanAssignment } from "../types/upskill-plan-assignment";

export const _svcUpskillPlanAssignment = createEntityService<UpskillPlanAssignment, Record<string, unknown>, Partial<UpskillPlanAssignment>, Partial<UpskillPlanAssignment>>({
	entity: "upskill-plan-assignment",
	namespace: "careerhub",
	ops: {
		list: { callerId: "upskill-plan-assignment-list", method: "GET", path: "/{profileEncId}/upskill-plan-assignment" },
		getById: { callerId: "upskill-plan-assignment-get-by-id", method: "GET", path: "/{profileEncId}/upskill-plan-assignment/{planId}" },
	},
});

export const getUpskillPlanAssignment = _svcUpskillPlanAssignment.getById;
export const listUpskillPlanAssignments = _svcUpskillPlanAssignment.list;
