// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { UserCalendar, UserCalendarListFilters } from "../types/user-calendar";

export const _svcUserCalendar = createEntityService<UserCalendar, UserCalendarListFilters, Partial<UserCalendar>, Partial<UserCalendar>>({
	entity: "user-calendar",
	namespace: "core",
	ops: {
		getById: { callerId: "user-calendar-event-get-by-id", method: "GET", path: "/user-calendar-events/{userCalendarEventId}" },
		batchFetch: { callerId: "user-calendar-event-batch-fetch", method: "POST", path: "/user-calendar-events/batch-fetch" },
		list: { callerId: "user-calendar-events-list-search", method: "GET", path: "/user-calendar-events" },
	},
});

export const getUserCalendar = _svcUserCalendar.getById;
export const listUserCalendars = _svcUserCalendar.list;
export const batchFetchUserCalendars = _svcUserCalendar.batchFetch;
