// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { UserMessage, UserMessageListFilters } from "../types/user-message";

export const _svcUserMessage = createEntityService<UserMessage, UserMessageListFilters, Partial<UserMessage>, Partial<UserMessage>>({
	entity: "user-message",
	namespace: "core",
	ops: {
		getById: { callerId: "user-messages-get-by-id", method: "GET", path: "/user-messages/{userMessageId}" },
		batchFetch: { callerId: "user-messages-batch-fetch", method: "POST", path: "/user-messages/batch-fetch" },
		list: { callerId: "user-messages-list-search", method: "GET", path: "/user-messages" },
	},
});

export const getUserMessage = _svcUserMessage.getById;
export const listUserMessages = _svcUserMessage.list;
export const batchFetchUserMessages = _svcUserMessage.batchFetch;
