// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { UserCampaign, UserCampaignListFilters } from "../types/user-campaign";

export const _svcUserCampaign = createEntityService<UserCampaign, UserCampaignListFilters, Partial<UserCampaign>, Partial<UserCampaign>>({
	entity: "user-campaign",
	namespace: "core",
	ops: {
		getById: { callerId: "user-campaigns-get-by-id", method: "GET", path: "/user-campaigns/{userCampaignId}" },
		batchFetch: { callerId: "user-campaigns-batch-fetch", method: "POST", path: "/user-campaigns/batch-fetch" },
		list: { callerId: "user-campaigns-list-search", method: "GET", path: "/user-campaigns" },
	},
});

export const getUserCampaign = _svcUserCampaign.getById;
export const listUserCampaigns = _svcUserCampaign.list;
export const batchFetchUserCampaigns = _svcUserCampaign.batchFetch;
