// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityService } from "../service-factory";
import type { User, UserListFilters } from "../types/user";

export const _svcUser = createEntityService<User, UserListFilters, Partial<User>, Partial<User>>({
	entity: "user",
	namespace: "core",
	ops: {
		getById: { callerId: "user-get-by-id", method: "GET", path: "/users/{userId}" },
		delete: { callerId: "user-delete", method: "DELETE", path: "/users/{userId}" },
		patch: { callerId: "user-patch", method: "PATCH", path: "/users/{userId}" },
		list: { callerId: "users-list-search", method: "GET", path: "/users" },
		create: { callerId: "user-create", method: "POST", path: "/users" },
		batchFetch: { callerId: "user-batch-fetch", method: "POST", path: "/users/batch-fetch" },
	},
});

export const getUser = _svcUser.getById;
export const listUsers = _svcUser.list;
export const batchFetchUsers = _svcUser.batchFetch;
export const createUser = _svcUser.create;
export const patchUser = _svcUser.patch;
export const deleteUser = _svcUser.delete;
