// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcEmployee as _svc } from "../services/employee.service";
import type { Employee, EmployeeListFilters } from "../types/employee";

const _h = createEntityHooks<Employee, EmployeeListFilters>("employee", _svc);

export const useEmployee = _h.useDetail;
export const useEmployees = _h.useList;
export const useBatchFetchEmployees = _h.useBatchFetch;
export const useCreateEmployee = _h.useCreate;
export const useUpdateEmployee = _h.useUpdate;
export const usePatchEmployee = _h.usePatch;
/** Get Employee Role — GET /employee-roles/{roleId} */
export const useGetByIdRoleEmployee = _h.makeOpQuery("getByIdRole");
/** Create Employee Role — POST /employee-roles */
export const useCreateRoleEmployee = _h.makeOpMutation("createRole");
/** List Recommended Mentors — GET /employees/{profileId}/recommended-mentors */
export const useListEmployeesRecommendedMentors = _h.makeOpQuery("listEmployeesRecommendedMentors");
/** List Employee Match Scores — GET /employees/role-match-score */
export const useListEmployeesRoleMatchScore = _h.makeOpQuery("listEmployeesRoleMatchScore");
