// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcAtsCandidate as _svc } from "../services/ats-candidate.service";
import type { AtsCandidate, AtsCandidateListFilters } from "../types/ats-candidate";

const _h = createEntityHooks<AtsCandidate, AtsCandidateListFilters>("ats-candidate", _svc);

export const useAtsCandidate = _h.useDetail;
export const useAtsCandidates = _h.useList;
export const useCreateAtsCandidate = _h.useCreate;
export const useUpdateAtsCandidate = _h.useUpdate;
export const usePatchAtsCandidate = _h.usePatch;
