// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcPosition as _svc } from "../services/position.service";
import type { Position, PositionListFilters } from "../types/position";

const _h = createEntityHooks<Position, PositionListFilters>("position", _svc);

export const usePosition = _h.useDetail;
export const usePositions = _h.useList;
export const useBatchFetchPositions = _h.useBatchFetch;
export const useCreatePosition = _h.useCreate;
export const useUpdatePosition = _h.useUpdate;
export const usePatchPosition = _h.usePatch;
/** List Matched Positions for Profile — GET /profiles/{profileId}/matched-positions */
export const useListSearchPosition = _h.makeOpQuery("listSearch");
