// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcOrgUnit as _svc } from "../services/org-unit.service";
import type { OrgUnit, OrgUnitListFilters } from "../types/org-unit";

const _h = createEntityHooks<OrgUnit, OrgUnitListFilters>("org-unit", _svc);

export const useOrgUnits = _h.useList;
/** List Foundational Data — GET /foundational-data */
export const useListSearchOrgUnit = _h.makeOpQuery("listSearch");
