// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcPerformanceFeedback as _svc } from "../services/performance-feedback.service";
import type { PerformanceFeedback, PerformanceFeedbackListFilters } from "../types/performance-feedback";

const _h = createEntityHooks<PerformanceFeedback, PerformanceFeedbackListFilters>("performance-feedback", _svc);

export const usePerformanceFeedback = _h.useDetail;
export const usePerformanceFeedbacks = _h.useList;
export const useCreatePerformanceFeedback = _h.useCreate;
/** Request Performance Feedback — POST /performance-feedback/request */
export const useCreateRequestPerformanceFeedback = _h.makeOpMutation("createRequest");
