// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcEventCandidateActivity as _svc } from "../services/event-candidate-activity.service";
import type { EventCandidateActivity } from "../types/event-candidate-activity";

const _h = createEntityHooks<EventCandidateActivity, Record<string, unknown>>("event-candidate-activity", _svc);

export const useEventCandidateActivity = _h.useDetail;
export const useBatchFetchEventCandidateActivities = _h.useBatchFetch;
