// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcProfileEventCalendar as _svc } from "../services/profile-event-calendar.service";
import type { ProfileEventCalendar, ProfileEventCalendarListFilters } from "../types/profile-event-calendar";

const _h = createEntityHooks<ProfileEventCalendar, ProfileEventCalendarListFilters>("profile-event-calendar", _svc);

export const useProfileEventCalendars = _h.useList;
