// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcEntityChangelog as _svc } from "../services/entity-changelog.service";
import type { EntityChangelog, EntityChangelogListFilters } from "../types/entity-changelog";

const _h = createEntityHooks<EntityChangelog, EntityChangelogListFilters>("entity-changelog", _svc);

export const useEntityChangelogs = _h.useList;
