// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcProfileApplication as _svc } from "../services/profile-application.service";
import type { ProfileApplication, ProfileApplicationListFilters } from "../types/profile-application";

const _h = createEntityHooks<ProfileApplication, ProfileApplicationListFilters>("profile-application", _svc);

export const useProfileApplication = _h.useDetail;
export const useProfileApplications = _h.useList;
export const useBatchFetchProfileApplications = _h.useBatchFetch;
