// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcOffer as _svc } from "../services/offer.service";
import type { Offer, OfferListFilters } from "../types/offer";

const _h = createEntityHooks<Offer, OfferListFilters>("offer", _svc);

export const useOffers = _h.useList;
