// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcEmailDeliveryFeedback as _svc } from "../services/email-delivery-feedback.service";
import type { EmailDeliveryFeedback, EmailDeliveryFeedbackListFilters } from "../types/email-delivery-feedback";

const _h = createEntityHooks<EmailDeliveryFeedback, EmailDeliveryFeedbackListFilters>("email-delivery-feedback", _svc);

export const useEmailDeliveryFeedback = _h.useDetail;
export const useEmailDeliveryFeedbacks = _h.useList;
export const useBatchFetchEmailDeliveryFeedbacks = _h.useBatchFetch;
