// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcJie as _svc } from "../services/jie.service";
import type { Jie, JieListFilters } from "../types/jie";

const _h = createEntityHooks<Jie, JieListFilters>("jie", _svc);

export const useJie = _h.useDetail;
export const useJies = _h.useList;
export const useCreateJie = _h.useCreate;
export const useUpdateJie = _h.useUpdate;
export const useDeleteJie = _h.useDelete;
/** Get Succession Plan — GET /insights */
export const useListJIEInsights = _h.makeOpQuery("listJIEInsights");
