// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcBooking as _svc } from "../services/booking.service";
import type { Booking, BookingListFilters } from "../types/booking";

const _h = createEntityHooks<Booking, BookingListFilters>("booking", _svc);

export const useBookings = _h.useList;
