// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcHrisEmployee as _svc } from "../services/hris-employee.service";
import type { HrisEmployee, HrisEmployeeListFilters } from "../types/hris-employee";

const _h = createEntityHooks<HrisEmployee, HrisEmployeeListFilters>("hris-employee", _svc);

export const useHrisEmployee = _h.useDetail;
export const useHrisEmployees = _h.useList;
export const useUpdateHrisEmployee = _h.useUpdate;
export const usePatchHrisEmployee = _h.usePatch;
