// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcProfile as _svc } from "../services/profile.service";
import type { Profile, ProfileListFilters } from "../types/profile";

const _h = createEntityHooks<Profile, ProfileListFilters>("profile", _svc);

export const useProfile = _h.useDetail;
export const useProfiles = _h.useList;
export const useBatchFetchProfiles = _h.useBatchFetch;
export const useCreateProfile = _h.useCreate;
export const useUpdateProfile = _h.useUpdate;
export const usePatchProfile = _h.usePatch;
export const useDeleteProfile = _h.useDelete;
/** Get Attachment — GET /profiles/{profileId}/attachments/{attachmentId} */
export const useGetByIdAttachmentProfile = _h.makeOpQuery("getByIdAttachment");
/** List Matched Candidates for Position — GET /positions/{positionId}/matched-candidates */
export const useListSearchProfile = _h.makeOpQuery("listSearch");
/** List Applicants — GET /position/{positionId}/applicants */
export const useListSearch2Profile = _h.makeOpQuery("listSearch2");
/** Upsert Application Stage — POST /profiles/{profileId}/application/stages */
export const useCreateStageProfile = _h.makeOpMutation("createStage");
