// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcSuccessionPlan as _svc } from "../services/succession-plan.service";
import type { SuccessionPlan, SuccessionPlanListFilters } from "../types/succession-plan";

const _h = createEntityHooks<SuccessionPlan, SuccessionPlanListFilters>("succession-plan", _svc);

export const useSuccessionPlan = _h.useDetail;
export const useSuccessionPlans = _h.useList;
export const useCreateSuccessionPlan = _h.useCreate;
export const usePatchSuccessionPlan = _h.usePatch;
export const useDeleteSuccessionPlan = _h.useDelete;
/** Get Recommended Successors — GET /succession_plans/{positionId}/recommended_successors */
export const useListSuccessorsSuccessionPlan = _h.makeOpQuery("listSuccessors");
/** List Succession Plan Incumbents — GET /succession_plans/{positionId}/incumbents */
export const useListIncumbentSuccessionPlan = _h.makeOpQuery("listIncumbent");
/** Create Succession Plan Successor — POST /succession_plans/{positionId}/successors */
export const useCreateSuccessorSuccessionPlan = _h.makeOpMutation("createSuccessor");
/** Patch Succession Plan Successor — PATCH /succession_plans/{positionId}/successors/{profileId} */
export const usePatchSuccessorSuccessionPlan = _h.makeOpMutation("patchSuccessor");
/** Delete Succession Plan Successor — DELETE /succession_plans/{positionId}/successors/{profileId} */
export const useDeleteSuccessorSuccessionPlan = _h.makeOpMutation("deleteSuccessor");
/** Create Succession Plan Caretaker — POST /succession_plans/{positionId}/caretakers */
export const useCreateCaretakerSuccessionPlan = _h.makeOpMutation("createCaretaker");
/** Delete Succession Plan Caretaker — DELETE /succession_plans/{positionId}/caretakers/{profileId} */
export const useDeleteCaretakerSuccessionPlan = _h.makeOpMutation("deleteCaretaker");
