// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcExtDemand as _svc } from "../services/ext-demand.service";
import type { ExtDemand, ExtDemandListFilters } from "../types/ext-demand";

const _h = createEntityHooks<ExtDemand, ExtDemandListFilters>("ext-demand", _svc);

export const useExtDemands = _h.useList;
