// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcDemand as _svc } from "../services/demand.service";
import type { Demand, DemandListFilters } from "../types/demand";

const _h = createEntityHooks<Demand, DemandListFilters>("demand", _svc);

export const useDemands = _h.useList;
/** List Matched Demands for Employee — GET /employees/{profileId}/matched-demands */
export const useListSearchDemand = _h.makeOpQuery("listSearch");
