// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcUserCalendar as _svc } from "../services/user-calendar.service";
import type { UserCalendar, UserCalendarListFilters } from "../types/user-calendar";

const _h = createEntityHooks<UserCalendar, UserCalendarListFilters>("user-calendar", _svc);

export const useUserCalendar = _h.useDetail;
export const useUserCalendars = _h.useList;
export const useBatchFetchUserCalendars = _h.useBatchFetch;
