// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcUserMessage as _svc } from "../services/user-message.service";
import type { UserMessage, UserMessageListFilters } from "../types/user-message";

const _h = createEntityHooks<UserMessage, UserMessageListFilters>("user-message", _svc);

export const useUserMessage = _h.useDetail;
export const useUserMessages = _h.useList;
export const useBatchFetchUserMessages = _h.useBatchFetch;
