// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcCareerhub as _svc } from "../services/careerhub.service";
import type { Careerhub } from "../types/careerhub";

const _h = createEntityHooks<Careerhub, Record<string, unknown>>("careerhub", _svc);

export const useCareerhub = _h.useDetail;
export const usePatchCareerhub = _h.usePatch;
/** Get Career Planner Role — GET /career-planner/{userEmail}/roles/{roleSection} */
export const useGetByIdCareerPlannerRolesCareerhub = _h.makeOpQuery("getByIdCareerPlannerRoles");
/** Get Skill Gap Analysis — GET /career-planner/{userEmail}/skills/skill-gap-analysis */
export const useGetByIdCareerPlannerSkillsCareerhub = _h.makeOpQuery("getByIdCareerPlannerSkills");
/** Get Recommended Courses — GET /career-planner/{userEmail}/courses/recommended-courses */
export const useGetByIdCareerPlannerCoursesCareerhub = _h.makeOpQuery("getByIdCareerPlannerCourses");
