// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcProfileFeedback as _svc } from "../services/profile-feedback.service";
import type { ProfileFeedback, ProfileFeedbackListFilters } from "../types/profile-feedback";

const _h = createEntityHooks<ProfileFeedback, ProfileFeedbackListFilters>("profile-feedback", _svc);

export const useProfileFeedback = _h.useDetail;
export const useProfileFeedbacks = _h.useList;
export const useBatchFetchProfileFeedbacks = _h.useBatchFetch;
