// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcUserCampaign as _svc } from "../services/user-campaign.service";
import type { UserCampaign, UserCampaignListFilters } from "../types/user-campaign";

const _h = createEntityHooks<UserCampaign, UserCampaignListFilters>("user-campaign", _svc);

export const useUserCampaign = _h.useDetail;
export const useUserCampaigns = _h.useList;
export const useBatchFetchUserCampaigns = _h.useBatchFetch;
