// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcEvent as _svc } from "../services/event.service";
import type { Event } from "../types/event";

const _h = createEntityHooks<Event, Record<string, unknown>>("event", _svc);

export const useEvent = _h.useDetail;
export const useEvents = _h.useList;
export const useBatchFetchEvents = _h.useBatchFetch;
