// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcProfileEntityApplication as _svc } from "../services/profile-entity-application.service";
import type { ProfileEntityApplication, ProfileEntityApplicationListFilters } from "../types/profile-entity-application";

const _h = createEntityHooks<ProfileEntityApplication, ProfileEntityApplicationListFilters>("profile-entity-application", _svc);

export const useProfileEntityApplication = _h.useDetail;
export const useProfileEntityApplications = _h.useList;
export const useBatchFetchProfileEntityApplications = _h.useBatchFetch;
