// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcHoliday as _svc } from "../services/holiday.service";
import type { Holiday, HolidayListFilters } from "../types/holiday";

const _h = createEntityHooks<Holiday, HolidayListFilters>("holiday", _svc);

export const useHolidays = _h.useList;
