// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcAsyncApiStatus as _svc } from "../services/async-api-status.service";
import type { AsyncApiStatus } from "../types/async-api-status";

const _h = createEntityHooks<AsyncApiStatus, Record<string, unknown>>("async-api-status", _svc);

export const useAsyncApiStatus = _h.useDetail;
