// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcAtsPosition as _svc } from "../services/ats-position.service";
import type { AtsPosition, AtsPositionListFilters } from "../types/ats-position";

const _h = createEntityHooks<AtsPosition, AtsPositionListFilters>("ats-position", _svc);

export const useAtsPosition = _h.useDetail;
export const useAtsPositions = _h.useList;
export const useCreateAtsPosition = _h.useCreate;
export const useUpdateAtsPosition = _h.useUpdate;
export const usePatchAtsPosition = _h.usePatch;
/** Upload ATS Position Attachments — POST /ats-systems/{systemId}/ats-positions/{atsPositionId}/attachments */
export const useCreateAttachmentsAtsPosition = _h.makeOpMutation("createAttachments");
