// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcResourceManagement as _svc } from "../services/resource-management.service";
import type { ResourceManagement, ResourceManagementListFilters } from "../types/resource-management";

const _h = createEntityHooks<ResourceManagement, ResourceManagementListFilters>("resource-management", _svc);

export const useResourceManagement = _h.useDetail;
export const useResourceManagements = _h.useList;
export const useDeleteResourceManagement = _h.useDelete;
/** Get Comments By External Entity Id And Type — GET /ext-entity-comments/{entityType}/{extEntityId} */
export const useListTypeResourceManagement = _h.makeOpQuery("listType");
/** Get Comments By Entity Id And Type — GET /entity-comments/{entityType}/{entityId} */
export const useListType2ResourceManagement = _h.makeOpQuery("listType2");
/** Batch Fetch Comments By Entity IDs — POST /entity-comments-batch-fetch */
export const useBatchGetByIdsIdsResourceManagement = _h.makeOpMutation("batchGetByIdsIds");
/** Batch Fetch Comments By External Entity IDs — POST /ext-entity-comments-batch-fetch */
export const useBatchGetByIdsIds2ResourceManagement = _h.makeOpMutation("batchGetByIdsIds2");
