// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcCourse as _svc } from "../services/course.service";
import type { Course, CourseListFilters } from "../types/course";

const _h = createEntityHooks<Course, CourseListFilters>("course", _svc);

export const useCourse = _h.useDetail;
export const useCourses = _h.useList;
export const useCreateCourse = _h.useCreate;
export const usePatchCourse = _h.usePatch;
export const useDeleteCourse = _h.useDelete;
