// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcProfileTag as _svc } from "../services/profile-tag.service";
import type { ProfileTag, ProfileTagListFilters } from "../types/profile-tag";

const _h = createEntityHooks<ProfileTag, ProfileTagListFilters>("profile-tag", _svc);

export const useProfileTag = _h.useDetail;
export const useProfileTags = _h.useList;
export const useBatchFetchProfileTags = _h.useBatchFetch;
