// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcHiringCompanyHiringCompany as _svc } from "../services/hiring-company-hiring-company.service";
import type { HiringCompanyHiringCompany } from "../types/hiring-company-hiring-company";

const _h = createEntityHooks<HiringCompanyHiringCompany, Record<string, unknown>>("hiring-company-hiring-company", _svc);

export const useHiringCompanyHiringCompany = _h.useDetail;
export const usePatchHiringCompanyHiringCompany = _h.usePatch;
