// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcCareerNavigator as _svc } from "../services/career-navigator.service";
import type { CareerNavigator, CareerNavigatorListFilters } from "../types/career-navigator";

const _h = createEntityHooks<CareerNavigator, CareerNavigatorListFilters>("career-navigator", _svc);

export const useCareerNavigator = _h.useDetail;
export const useCareerNavigators = _h.useList;
