// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcUser as _svc } from "../services/user.service";
import type { User, UserListFilters } from "../types/user";

const _h = createEntityHooks<User, UserListFilters>("user", _svc);

export const useUser = _h.useDetail;
export const useUsers = _h.useList;
export const useBatchFetchUsers = _h.useBatchFetch;
export const useCreateUser = _h.useCreate;
export const usePatchUser = _h.usePatch;
export const useDeleteUser = _h.useDelete;
