// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcTalentPool as _svc } from "../services/talent-pool.service";
import type { TalentPool } from "../types/talent-pool";

const _h = createEntityHooks<TalentPool, Record<string, unknown>>("talent-pool", _svc);

export const useCreateTalentPool = _h.useCreate;
