// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcExtAiInterview as _svc } from "../services/ext-ai-interview.service";
import type { ExtAiInterview } from "../types/ext-ai-interview";

const _h = createEntityHooks<ExtAiInterview, Record<string, unknown>>("ext-ai-interview", _svc);

export const useExtAiInterviews = _h.useList;
export const useCreateExtAiInterview = _h.useCreate;
/** Get Interview Feedback Link — GET /ext-systems/{systemId}/ext-ai-interview/interview-feedback-link */
export const useListLinkExtAiInterview = _h.makeOpQuery("listLink");
