// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcInsight as _svc } from "../services/insight.service";
import type { Insight, InsightListFilters } from "../types/insight";

const _h = createEntityHooks<Insight, InsightListFilters>("insight", _svc);

export const useInsights = _h.useList;
export const useCreateInsight = _h.useCreate;
/** Get Employee Diversity Insights — GET /diversity/employees */
export const useListEmployeesDiversityInsights = _h.makeOpQuery("listEmployeesDiversityInsights");
