// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcConnectors as _svc } from "../services/connectors.service";
import type { Connectors } from "../types/connectors";

const _h = createEntityHooks<Connectors, Record<string, unknown>>("connectors", _svc);

export const useConnectorses = _h.useList;
export const useCreateConnectors = _h.useCreate;
/** Get OAuth Access Token — GET /oauth-access-token */
export const useListTokenConnectors = _h.makeOpQuery("listToken");
