// Generated by _generator/generate.ts. Do not hand-edit.
import { createEntityHooks } from "../hooks-factory";
import { _svcProfileNote as _svc } from "../services/profile-note.service";
import type { ProfileNote, ProfileNoteListFilters } from "../types/profile-note";

const _h = createEntityHooks<ProfileNote, ProfileNoteListFilters>("profile-note", _svc);

export const useProfileNote = _h.useDetail;
export const useProfileNotes = _h.useList;
export const useBatchFetchProfileNotes = _h.useBatchFetch;
export const useCreateProfileNote = _h.useCreate;
